### ISSUE TITLE
advanced_nic role: NM_MANAGED must be set to false in RHEL7

### ISSUE THREAD

**Issue by jpm38** [bluebanquise/bluebanquise#131]
The ifcfg.j2 template sets the NM_MANAGED flag to yes whatever the operating system installed on the host.
For nodes running in RHEL7, the NM_MANAGED MUST be set to no.

**Comment by actatux** [comment]
@oxedions where does this NM_MANAGED come from? I can't find it documented in /usr/share/doc/initscripts*/sysconfig.txt for both el7 and el8.

**Comment by jpm38** [comment]
I don't know but it is used in the role advanced_nic:
template ifcfg.j2
#### Blue Banquise file ####
## {{ansible_managed}}

{# 1. First the name and default parameters. #}
NAME={{item}}
DEVICE={{item}}
{% if (network_interfaces[item]['autoconnect'] is defined and not none) and (network_interfaces[item]['autoconnect'] == false) %}
ONBOOT=no
{% else %}
ONBOOT=yes
{% endif %}
NM_MANAGED=yes
BOOTPROTO=none

**Comment by jpm38** [comment]
It seems that NM_CONTROLLED is the parameter name documented.

**Comment by actatux** [comment]
Does it change the behavior when you change NM_MANAGED ?

**Comment by jpm38** [comment]
Yes, when setting NM_MANAGED to no in RHEL7 , the interface is configured in static mode as expected.

**Comment by oxedions** [comment]
@actatux We used to set NM_MANAGED to no in RHEL 7.
But in RHEL 8, it is mandatory (you can even skip it, I let it to clarify configuration).

**Comment by oxedions** [comment]
This is NM_CONTROLLED, my bad ;-)

**Comment by actatux** [comment]
Still strange changing NM_MANAGED to no in EL7 changes the behaviour. I will dig further.

**Comment by actatux** [comment]
I don't find any reference to NM_MANAGED in https://github.com/fedora-sysv/initscripts.
Anyway, I will propose a tunable to toggle NM_CONTROLLED between `yes` and `no`. It will default to `yes` to keep the default RHEL behaviour.
