### ISSUE TITLE
Documentation is missing some parts

### ISSUE THREAD

**Issue by oxedions** [bluebanquise/bluebanquise#144]
Missing parts:
- [x] Ansible training do not cover tasks (when, loop, with_items, etc)
- [ ] equipment_profiles values are not properly explained in the documentation, and available values are not provided.
- [x] Web site upgrade with new documentation

**Comment by johnnykeats** [comment]
Seen website has been upgraded. Done?

**Comment by oxedions** [comment]
Yes, updated.

**Comment by oxedions** [comment]
Moved to general dashboard.
