### ISSUE TITLE
dns_server role: remove "@ IN A 10.0.0.1  mngt IN A 10.0.0.1" from forward template

### ISSUE THREAD

**Issue by jpm38** [bluebanquise/bluebanquise#146]
These 3 lines are not needed and are leading the the dns_server role failing in chroot context execution.

diff -r roles/core/dns_server/templates/forward.j2 roles.bkp/core/dns_server/templates/forward.j212a13,15> @ IN A {{network_interfaces[j2_node_main_network_interface]['ip4']}}>> {{inventory_hostname}} IN A {{network_interfaces[j2_node_main_network_interface]['ip4']}}
--

**Comment by actatux** [comment]
Hello @jpm38 , there is a proposal in #158, does it solve your issue?
PR is still pending for reviews.

**Comment by jpm38** [comment]
Hello @actatux 
Yes, it's perfect.
thanks a lot
