### ISSUE TITLE
time: do not define both server and pool together

### ISSUE THREAD

**Issue by actatux** [bluebanquise/bluebanquise#166]
The role `time` defines both `server` and `pool` in chrony configuration if both are defined in the inventory.

```
[root@management1 ~]# head -6 /etc/chrony.conf 
#### Blue Banquise file ####
## Ansible managed: modified on 2020-04-07 03:52:27 by root on management1

# External servers/pool if asked
server 0.fr.pool.ntp.org
pool pool.ntp.org iburst maxsources 3
```

We should change this behaviour to define either server(s) or pool. I would default to pool.

See:
 - https://chrony.tuxfamily.org/faq.html#_what_is_the_minimum_recommended_configuration_for_an_ntp_client
 - https://help.fortinet.com/coyotepoint/10-3-2/Content/NetConfig/Selecting_an_NTP_Server.htm

**Comment by oxedions** [comment]
Agreed on my side, pool should go first.

**Comment by johnnykeats** [comment]
Good catch.

**Comment by actatux** [comment]
Clients with external_time configuration + services_ip.time_ip in their main network:
```
# External pool
pool pool.ntp.org iburst maxsources 3
# Source server to bind to
server 10.11.0.1
```
or
```
# External servers
server 0.pool.ntp.org
server 1.pool.ntp.org
server 2.pool.ntp.org
# Source servers to bind to
server 10.12.0.1
server 10.12.0.2
```

Should we consider this as a bug or tell users they need to remove services_ip.time_ip from their inventory if they want to use external servers?
I would set external_time if defined, otherwise default to services_ip.time_ip.

**Comment by actatux** [comment]
NTP servers' chrony.conf include the local `server 127.127.1.0`. This is a ntpd-specific configuration which is not supported in chrony. I will remove it.

Example without any pool or server in the conf:
```
# egrep -c "^server|^pool" /etc/chrony.conf 
0
# chronyc sources
210 Number of sources = 0
MS Name/IP address         Stratum Poll Reach LastRx Last sample               
=====================================================================
# chronyc tracking | grep Reference
Reference ID    : 7F7F0101 ()
# printf "%d.%d.%d.%d\n" 0x7f 0x7f 0x01 0x01
127.127.1.1
```


See:
- https://chrony.tuxfamily.org/doc/2.1/manual.html#local-directive
- https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/sect-setting_up_chrony_for_different_environments#sect-Setting_up_chrony_for_a_system_in_an_isolated_network
