### ISSUE TITLE
roles/core/time - not working on ubi8 image

### ISSUE THREAD

**Issue by strus38** [bluebanquise/bluebanquise#167]
Hi
molecule testing is showing the following error:
` TASK [time : Install packages] *************************************************
fatal: [instance]: FAILED! => {"changed": false, "failures": ["No package chrony available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}`

**Comment by actatux** [comment]
Chrony is not available in the public CDN for UBI: https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi8/8/x86_64/baseos/os/Packages/c/

To use this `ubi8` image, we would need a valid RHEL subscription to be granted access to RHEL repositories.

**Comment by strus38** [comment]
Ok, commented out the ubi7/ubi8 lines in travis.
