### ISSUE TITLE
Lmod role

### ISSUE THREAD

**Issue by lemoinepierre** [bluebanquise/bluebanquise#181]
Hi,
it looks like BB does not include anything related to [Lmod module](https://github.com/TACC/Lmod).

Such a tool would be really convinient to easily manage different version of same compilers or application.
Do you think you can integrate it in BB?

**Comment by oxedions** [comment]
Dear @lemoinepierre 

Thank you for this request.

Indeed, BB is missing the user side, and I find Environment Module a bit old. I know customers using Lmod, so I will have a look :-)

Give me few days to investigate this.

**Comment by johnnykeats** [comment]
Also using Lmod.
+1 on this. Need to allow default and customs paths.

**Comment by oxedions** [comment]
Moved to general dashboard.
