### ISSUE TITLE
Need to exclude molecules rst from documentation

### ISSUE THREAD

**Issue by johnnykeats** [bluebanquise/bluebanquise#195]
INSTALL.rst files end up in documentation.
Need exclude pattern in sphinx conf.py.

**Comment by oxedions** [comment]
Hello JK.
But non added rst files should not be taken into account, am I wrong ?

**Comment by oxedions** [comment]
Hello JK.
But non added rst files should not be taken into account, am I wrong ?

**Comment by johnnykeats** [comment]
Nop, will pollute final _build.
Simply need to add an **/molecule in exclude patterns.

**Comment by oxedions** [comment]
Ok, got it. Strange, for me that sphinx gather also not asked files.

**Comment by johnnykeats** [comment]
Check make logs and _build output.

**Comment by oxedions** [comment]
Ok, I see. Can you handle the PR ?

**Comment by johnnykeats** [comment]
Sure
