### ISSUE TITLE
Text error in documentation

### ISSUE THREAD

**Issue by vdi38** [bluebanquise/bluebanquise#198]
Chapter 2.1.3.2 List
...
{% if my_names_list %}
the list is not empty
{% else %}
the list is empty %} <---
{% endif %}
...

**Comment by oxedions** [comment]
Hello @vdi38 

Thanks for this issue :-)

I will correct it as soon as possible. If you find more, please do not hesitate.

**Comment by oxedions** [comment]
`Then, create file /etc/ansible/inventory/group_vars/slave/myship.yml with the following content:`
Should be slaves

**Comment by oxedions** [comment]
Solved ;-)
