### ISSUE TITLE
Typo issue in DNS task

### ISSUE THREAD

**Issue by oxedions** [bluebanquise/bluebanquise#214]
At both places, new DNS role use `management_network_naming` instead of `management_networks_naming`, so a simple missing s :-)

Example:
`    dns_master: "{{ networks[management_network_naming+'1-1'].services_ip.dns_ip }}"`

Found it when adding OpenSuse to it.

**Comment by actatux** [comment]
My bad...coding late at night. ;-)

**Comment by oxedions** [comment]
Coding at night is the best :laughing:
