### ISSUE TITLE
Date in templates header seems wrong

### ISSUE THREAD

**Issue by actatux** [bluebanquise/bluebanquise#239]
I noticed this several times but did not take time to check yet.

The date in the header "Ansible managed: modified on ..." is not the modification date of the file on-disk, but the modification date of the template:

```
[root@management1 bluebanquise]# head /etc/hosts
#### Blue Banquise file ####
## Ansible managed: modified on 2020-05-28 22:47:28 by root on management1
```
```
[root@management1 bluebanquise]# stat /etc/hosts |grep Modify
Modify: 2020-05-29 01:28:34.531858543 +0200
[root@management1 bluebanquise]# stat roles/core/hosts_file/templates/hosts.j2 |grep Modify
Modify: 2020-05-28 22:47:28.393813315 +0200
```
As an admin, I am expecting the modification date of the file on-disk (template + processing).

**Comment by actatux** [comment]
Note that it is impossible to get the date of the change on-disk since Ansible generates the file from template + data before comparing with the destination file.
The question here is: is it relevant to print this date in the header?

**Comment by johnnykeats** [comment]
See multiple exchanges on this behavior:
https://github.com/ansible/ansible/issues/5317
https://github.com/ansible/ansible/issues/17947

Some need files to always update when time stamp, other not.

On my system, header indeed keeps at first time file was generated, which could introduce dangerous misunderstanding.

Suggest this, ansible.cfg:

`ansible_managed = Ansible managed file, do not edit`

If ok, will take care of it.

**Comment by actatux** [comment]
I do agree with your suggestion.
