### ISSUE TITLE
core/dns_server missing external_hosts support

### ISSUE THREAD

**Issue by gauthierdelerce** [bluebanquise/bluebanquise#245]
Hello,
The role doesn't create entries for the external hosts defined in group_vars/all/general_settings/external.yml.
The readme mentions 
"readme.rst:External hosts defined in *group_vars/all/general_settings/external.yml* at variable **external_hosts** will be automatically added in the dns configuration "
but there is no reference to external_hosts in the templates.

Could you re-add in the templates theses lines : 

diff --git a/roles/core/dns_server/templates/reverse.j2 b/roles/core/dns_server/templates/reverse.j2
index 91782ed..7920cca 100644
--- a/roles/core/dns_server/templates/reverse.j2
+++ b/roles/core/dns_server/templates/reverse.j2
@@ -30,3 +30,9 @@ $INCLUDE "/var/named/reverse.soa"
 {% endif %}
 {% endif %}
 {% endfor %}
+
+;## External hosts
+
+{% for host in external_hosts %}
+{{external_hosts[host].split('.')[3]}}.{{external_hosts[host].split('.')[2]}}.{{external_hosts[host].split('.')[1]}}.{{extern
+{% endfor %}

diff --git a/roles/core/dns_server/templates/forward.j2 b/roles/core/dns_server/templates/forward.j2
index 281e43c..e241874 100644
--- a/roles/core/dns_server/templates/forward.j2
+++ b/roles/core/dns_server/templates/forward.j2
@@ -35,3 +35,10 @@ $INCLUDE "/var/named/forward.soa"
 {% endif %}
 {% endif %}
 {% endfor %}
+
+;## External hosts
+
+{% for host in external_hosts %}
+{{host}} IN A {{external_hosts[host]}}
+{% endfor %}
+

Thanks

**Comment by actatux** [comment]
Hi Gauthier,

Can you explain your use case?
I removed the external_hosts because [it was not producing the expected result](https://github.com/bluebanquise/bluebanquise/pull/158#issuecomment-613439062).

**Comment by actatux** [comment]
You may need to configure DNS forwarding on your DNS servers to resolve external domains?

**Comment by gauthierdelerce** [comment]
Sure, but we also have to resolve IP which are not defined in any DNS servers.
I prefer to use /etc/hosts and dns anyway, so it's a good reason to create /etc/hosts.

**Comment by actatux** [comment]
> The readme mentions
> "readme.rst:External hosts defined in _group_vars/all/general_settings/external.yml_ at variable **external_hosts** will be automatically added in the dns configuration "
> but there is no reference to external_hosts in the templates.

This sentence will be removed with PR #241.
