### ISSUE TITLE
Support secured SSL connection to connect to LDAP server in role addons/openldap_client

### ISSUE THREAD

**Issue by gavillom** [bluebanquise/bluebanquise#287]
Hey !

I think it would be glad to have a way to configure LDAP client to connect to a server through SSL connection.
Actually, it's not currently possible to do any configuration in the inventory to match this requirement.

Mathis

PS : nice feature also to have a way to deploy LDAP server secured with SSL :-)

**Comment by oxedions** [comment]
Dear @gavillom 

Thank you for this request.

I was also considering adding ssl to ldap, and an GUI: https://github.com/kakwa/ldapcherry

However, RedHat removed OnpenLDAP from all its repositories, and so did Centos and the EPEL.

So do you still confirm this need for RHEL/Centos 8+ versions, considering this ?

With my best regards

Ox

**Comment by gavillom** [comment]
Well if RedHat removed support of OpenLDAP server, would be great to support configuration of SSSD with SSL LDAP server (client part only). And forget server side.

SSSD for LDAP server configuration is still supported right ?

We've implemented such needs on our side. We also have the ability to configure several LDAP server. Do you want us to create the PR ?

Mathis

**Comment by oxedions** [comment]
Dear @gavillom 

Yes, it would be very beneficial to other users if you accept to share your code 😊

Ox

**Comment by johnnykeats** [comment]
Dear @gavillom , Dear @oxedions 

Seems done with SSSD role.

Closing.
