### ISSUE TITLE
[dhcp-server] python-netaddr RPM missing

### ISSUE THREAD

**Issue by hmeAtos** [bluebanquise/bluebanquise#302]
Hello,

The role of `dhcp_server `crashes because the RPM is missing.

```
TASK [dhcp_server : template █ Generate /etc/dhcp/dhcpd.networks.conf] *********
Thursday 30 July 2020 20:01:34 +0200 (0:00:00.596) 0:00:22.986 *********
fatal: [wolfi01]: FAILED! => changed=false
msg: 'AnsibleFilterError: The ipaddr filter requires python''s netaddr be installed on the ansible controller'
```

I saw that a commit: delete this RPM
So I propose:
- go back and re-add this RPM in the `dhcp_server `role
- indicate in the documentation that this RPM is missing and that it must be installed manually before launching the playbooks

Regards,
 @hmeAtos

**Comment by btravouillon** [comment]
This package is required on the Ansible controller where the `ipaddr` filter is used, not on the dhcp server. You can configure the ansible controllers for the stack with the role `core/bluebanquise` which will install all the required dependencies for your OS.

See RHEL8 vars below as an example:
https://github.com/bluebanquise/bluebanquise/blob/737b401249a58706b281aab074e412635a2bab7c/roles/core/bluebanquise/vars/RedHat_8.yml#L1-L5

The example playbooks for management nodes reflect this:
https://github.com/bluebanquise/bluebanquise/blob/737b401249a58706b281aab074e412635a2bab7c/resources/examples/simple_cluster/playbooks/managements.yml#L16

The package should be installed during the setup of the BlueBanquise controller:
https://github.com/bluebanquise/bluebanquise/blob/2b0572ff796a133856ecd455e6d8c5b6f9dce094/resources/documentation/deploy_bluebanquise.rst#L84-L89

Hope this helps.
