### ISSUE TITLE
/etc/alertmanager/alertmanager.yml "do not edit"

### ISSUE THREAD

**Issue by sobrase** [bluebanquise/bluebanquise#346]
There is currently no way to customise /etc/alertmanager/alertmanager.yml using the ansible inventory, yet the is a do not edit line in the file, which contains default smtp values

**Comment by btravouillon** [comment]
Hello @sobrase,

Thank you for reporting.
This is indeed a template managed by Ansible, one can define some values in the inventory:
https://github.com/bluebanquise/bluebanquise/blob/6dd442c228cb8657e074023edd78b573abbf7b7a/roles/addons/prometheus_server/templates/alertmanager.yml.j2#L11-L13

However, you are right, it needs additional variables. Would you be able to open a PR with a proposal? We can discuss implementation in this issue first.

**Comment by oxedions** [comment]
See https://github.com/bluebanquise/community/pull/14 which will solve this issue.
