### ISSUE TITLE
Environment to test BlueBanquise

### ISSUE THREAD

**Issue by nqb** [bluebanquise/bluebanquise#358]
Hello,

I have seen that there is a repository managed by @btravouillon:  https://github.com/btravouillon/bluebanquise-vagrant that can be used to test BlueBanquise using Vagrant.

Any plan to add it directly in BlueBlanquise official repository ?

**Comment by btravouillon** [comment]
Hello @nqb,

We discussed this with @oxedions, there is a plan now. 😄 
Thanks for the idea.

Did you test it already?

**Comment by btravouillon** [comment]
Done: https://github.com/bluebanquise/bluebanquise-vagrant
I also commited and pushed some changes required for BlueBanquise 1.3.0.

**Comment by nqb** [comment]
Thanks @btravouillon and also thanks for examples added.
