### ISSUE TITLE
snmp_exporter fails to start

### ISSUE THREAD

**Issue by btravouillon** [bluebanquise/bluebanquise#366]
## Description

The snmp_exporter.service fails to start.

```
# systemctl status snmp_exporter
● snmp_exporter.service - snmp_exporter
   Loaded: loaded (/etc/systemd/system/snmp_exporter.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2020-09-12 17:38:33 EDT; 1min 2s ago
  Process: 40244 ExecStart=/usr/local/bin/snmp_exporter --config.file=/etc/snmp_exporter/snmp_config.yml (code=exited, status=1/FAILURE)
 Main PID: 40244 (code=exited, status=1/FAILURE)

Sep 12 17:38:33 management1 systemd[1]: Started snmp_exporter.
Sep 12 17:38:33 management1 systemd[1]: snmp_exporter.service: Main process exited, code=exited, status=1/FAILURE
Sep 12 17:38:33 management1 systemd[1]: snmp_exporter.service: Failed with result 'exit-code'.
```

The journal reports an error parsing the config file:

```
Sep 12 17:38:33 management1 snmp_exporter[40244]: level=error ts=2020-09-12T21:38:33.192Z caller=main.go:156 msg="Error parsing config file" err="open /etc/snmp_exporter/snmp_config.yml: no such file or directory"
```

Indeed this file does not exist.
The role in charge of snmp_exporter installation should create the appropriate configuration file.

## Info

OS: CentOS 8.2
Branch: stable-1.3
snmp_exporter-0.18.0-1.el8.x86_64

**Comment by oxedions** [comment]
This one is a bit tricky.
It must be generated using a dedicated tool: https://github.com/bluebanquise/bluebanquise/blob/master/resources/documentation/monitoring/snmp_exporter.rst

Maybe we could generate a "null" configuration file with the role, if and only it does not exist, then after that admin is in charge of the file (role will no more touch it if exist).
Other possibility, admin have to put a static file in "files" folder of the role if activation snmp.

**Comment by btravouillon** [comment]
[Upstream project](https://github.com/prometheus/snmp_exporter) provides a default `snmp.yml` config file.
We can either:

1. Provide the upstream `snmp.yml` config file in the RPM (infra)
2. Provide our own `snmp.yml` config file in the RPM (infra)
3. Add a task to this role that will check if `snmp.yml` exists and fail if it doesn't, with a message similar to "_snmp.yml config file not found. Please refer to the documentation to generate one._".
4. Enhance this role to run the generator (input data in inventory).

**Comment by oxedions** [comment]
Stalling this until rewamp of prometheus_server/client role scheduled.

**Comment by oxedions** [comment]
I will integrate point 3 into new Prometheus PR https://github.com/bluebanquise/community/pull/14
