### ISSUE TITLE
Documentation: diskless livenet needs some fixes - minor

### ISSUE THREAD

**Issue by strus38** [bluebanquise/bluebanquise#374]
URL: https://bluebanquise.com/documentation/index.html

1. Section: 11.3.3.2
ISSUE1: point 2 - instead of `cp /boot/<kernels to use for diskless nodes> /var/www/html/preboot_execution_environment/diskless/kernels/` we should put `cp /boot/<kernels to use for diskless nodes vmlinuz.XX> /var/www/html/preboot_execution_environment/diskless/kernels/`

ISSUE2: point 3 the real output is:
```
# disklessset
BlueBanquise Diskless manager
 1 - List available kernels
 2 - Generate a new initramfs
 3 - Generate a new diskless image
 4 - Manage existing diskless images
-->: 1
[INFO] Loading kernels from /var/www/html/preboot_execution_environment/diskless/kernels/

Available kernels:
    │
    └── vmlinuz-4.18.0-193.14.2.el8_2.x86_64 - missing initramfs-kernel-4.18.0-193.14.2.el8_2.x86_64
```

ISSUE3: in point 6, the output is:
```
Select kernel:
 1 - vmlinuz-4.18.0-193.14.2.el8_2.x86_64
-->: 1
Please enter image name ?
-->: livenet1
Please enter clear root password of the new image: root
[INFO] Entering livenet dedicated part.
Please select livenet image generation profile:
 1 - Standard: core
 2 - Small: openssh, dnf and NetworkManager
 3 - Minimal: openssh only
 4 - Custom: core + selection of additional packages
-->: 1
Please choose image size:
(supported units: M=1024*1024, G=1024*1024*1024)
(Example: 5120M or 5G)
-->: 5G
Enter path to SSH public key (left empty to disable key injection):
-->: /root/.ssh/id_rsa.pub
Do you want to activate SELinux inside the image?
Enter yes or no: yes
Do you want to create a new livenet image with the following parameters:
  Image name:           livenet1
  Kernel version:       vmlinuz-4.18.0-193.14.2.el8_2.x86_64
  Root password:        root
  Image profile:        1
  Image size:           5120M
  SSH pubkey:           /root/.ssh/id_rsa.pub
  Enable SELinux:       yes
Confirm ? Enter yes or no: yes
```

**Comment by oxedions** [comment]
Dear @strus38 

Thank you for this feedback. I will update the readme.

**Comment by btravouillon** [comment]
> 1. Section: 11.3.3.2
>    ISSUE1: point 2 - instead of `cp /boot/<kernels to use for diskless nodes> /var/www/html/preboot_execution_environment/diskless/kernels/` we should put `cp /boot/<kernels to use for diskless nodes vmlinuz.XX> /var/www/html/preboot_execution_environment/diskless/kernels/`
> 

The kernel file names all start with `vmlinuz-`, we can consider `cp /boot/vmlinuz-<kernel release to use for diskless nodes> /dest/`.

> ISSUE2: point 3 the real output is:
> 
> ```
> # disklessset
> BlueBanquise Diskless manager
>  1 - List available kernels
>  2 - Generate a new initramfs
>  3 - Generate a new diskless image
>  4 - Manage existing diskless images
> -->: 1
> [INFO] Loading kernels from /var/www/html/preboot_execution_environment/diskless/kernels/
> 
> Available kernels:
>     │
>     └── vmlinuz-4.18.0-193.14.2.el8_2.x86_64 - missing initramfs-kernel-4.18.0-193.14.2.el8_2.x86_64
> ```

Indeed, still true.

> 
> ISSUE3: in point 6, the output is:
> 
> ```
> Select kernel:
>  1 - vmlinuz-4.18.0-193.14.2.el8_2.x86_64
> -->: 1
> Please enter image name ?
> -->: livenet1
> Please enter clear root password of the new image: root
> [INFO] Entering livenet dedicated part.
> Please select livenet image generation profile:
>  1 - Standard: core
>  2 - Small: openssh, dnf and NetworkManager
>  3 - Minimal: openssh only
>  4 - Custom: core + selection of additional packages
> -->: 1
> Please choose image size:
> (supported units: M=1024*1024, G=1024*1024*1024)
> (Example: 5120M or 5G)
> -->: 5G
> Enter path to SSH public key (left empty to disable key injection):
> -->: /root/.ssh/id_rsa.pub
> Do you want to activate SELinux inside the image?
> Enter yes or no: yes
> Do you want to create a new livenet image with the following parameters:
>   Image name:           livenet1
>   Kernel version:       vmlinuz-4.18.0-193.14.2.el8_2.x86_64
>   Root password:        root
>   Image profile:        1
>   Image size:           5120M
>   SSH pubkey:           /root/.ssh/id_rsa.pub
>   Enable SELinux:       yes
> Confirm ? Enter yes or no: yes
> ```

The readme has been modified since, the HTML documentation needs an update.
