### ISSUE TITLE
Ports used in roles are not always configurable

### ISSUE THREAD

**Issue by strus38** [bluebanquise/bluebanquise#396]
All ports used in roles should be variables set by default in the role to their default standard values.
Inventories should be able to overwrite those values to custom ones when needed.
The README of the role shoul dlist the port and matching service with the default value so users know what they can change.

Thanks!

**Comment by btravouillon** [comment]
Indeed, it would be nice to define such parameters in `defaults/main.yml` for the roles. I would be pleased to review any PR implementing this.

**Comment by oxedions** [comment]
Dear @strus38 

Do you wish to also update other roles, or is rsyslog enough on your side ?

**Comment by strus38** [comment]
I did not find any other important yet... So let's move on.
