### ISSUE TITLE
cool project!

### ISSUE THREAD

**Issue by MalloZup** [bluebanquise/bluebanquise#409]
Bonjour guys, :)

I come across this project recently.
Let me introduce myself. 

I'm one of the maintainer of the `exporter` you are using:
https://github.com/ClusterLabs/ha_cluster_exporter 

So it is always cool to see one opensource project developed is getting used also from opensource projects.

I was  asking myself if you need any help or do you have any problem with the exporter that is worth to talk.

Recently we have also the dashboard based on the exporter:
https://github.com/ClusterLabs/ha_cluster_exporter/blob/master/dashboards/README.md

You can use the rpm or download them the via grafana.com

If you have any question with openSUSE integration or with the monitoring stack, please let me know, I will be glad to help.

In case you don't know we also recently working on a separated opensource project to deploy only ha-cluster via `salt-call` locally.

https://github.com/SUSE/pacemaker-deploy this works with libvirt 

I really like your comprehensive documentation, well done :+1: 

Best

**Comment by oxedions** [comment]
Dear @MalloZup 

Thanks a lot ! 😊 
And thank you for the ha_cluster_exporter.

Well, in fact I had a question. Let me open an issue on your git 🙂

**Comment by oxedions** [comment]
https://github.com/ClusterLabs/ha_cluster_exporter/issues/177

**Comment by MalloZup** [comment]
@oxedions  I'm closing this pr . for any info or even feature requests, feel free to reach out ! 

bye and have fun!

**Comment by oxedions** [comment]
Yes of course ! We will contact you if we have any needs 🙂 
Same on your side.

Thanks a lot, and have fun too !
