### ISSUE TITLE
[Doc] max_lease_time and default_lease_time are not used anymore

### ISSUE THREAD

**Issue by gavillom** [bluebanquise/bluebanquise#422]
Hi,

In documentation https://bluebanquise.com/documentation/roles.html#id16 related to dhcp_server role configuration, it's written : 

"Finally, note that the following parameters can be set in the inventory (group_vars/all/general_settings/network.yml):

- default_lease_time

- max_lease_time

Consider increasing the default values once your network is production ready."

While these variables are not used anymore. Should be replated by **advanced_dhcp_server_default_lease_time** and
**advanced_dhcp_server_max_lease_time**

Mathis

**Comment by btravouillon** [comment]
Indeed, both are documented with the correct name in https://bluebanquise.com/documentation/roles.html#id17.

Should we remove this section (redundant with Input / Optional inventory vars) or update the name of the variables?

**Comment by btravouillon** [comment]
Also note that these are documented in role **dhcp_server** but not in **advanced_dhcp_server**.

**Comment by gavillom** [comment]
> Indeed, both are documented with the correct name in https://bluebanquise.com/documentation/roles.html#id17.
> 
> Should we remove this section (redundant with Input / Optional inventory vars) or update the name of the variables?

Yes we can remove. Not sure it's really important to keep it, while it's documented below.

**Comment by gavillom** [comment]
> Also note that these are documented in role **dhcp_server** but not in **advanced_dhcp_server**.

I think it would be great to document variable (which seems to be different then dhcp_server).

**Comment by oxedions** [comment]
In the advanced dhcp server, readme:
`
Please read first documentation of the standard dhcp server role. Advanced dhcp server provides sames features than standard dhcp server role, but with more options.`

So I do not think we need to document it in the advanced dhcp server.

**Comment by oxedions** [comment]
Please check https://github.com/bluebanquise/bluebanquise/pull/441

**Comment by btravouillon** [comment]
Is there any topic left to address in this ticket?

**Comment by oxedions** [comment]
I think not. I will close it for now, and we can reopen if needed.
