### ISSUE TITLE
repositories_client role idempotency

### ISSUE THREAD

**Issue by andriimua** [bluebanquise/bluebanquise#455]
Hi all,

if you want to remove or rename previously created repository it won't remove it on the clients side.

for example, it can be implemented with additinal task  _remove_repositories_ using variable like _repositories_to_remove:_ that can contain list of repositories that should be removed.

**Comment by andriimua** [comment]
in case of **state** parameter it will delete every repository that weer created manually. 

in some cases it could be a problem.

**Comment by btravouillon** [comment]
Can you test #458?
It will only ensure repositories defined with `state: absent` do not exist. It should not delete any repository created manually.

**Comment by andriimua** [comment]
@btravouillon sorry, it was misunderstanding from my side, I supposed that we were discussing `state: present` :)

**Comment by btravouillon** [comment]
No problem. Since #458 merged to master, I guess we can close this feature request?

**Comment by oxedions** [comment]
Ok on my side 🙂 
This is perfect.
