### ISSUE TITLE
centos8 openldap_server role - does not work and will not.

### ISSUE THREAD

**Issue by strus38** [bluebanquise/bluebanquise#465]
Hi

Using master branch of bluebanquise.
Installed the management1 following the doc, then trying to deploy the openldap_server role.
Issue:
```
TASK [openldap_server : package █ Install openldap-servers openldap-clients httpd phpldapadmin python3-libselinux python3-policycoreutils packages] ***
Saturday 07 November 2020  17:00:04 +0100 (0:00:00.048)       0:00:18.719 *****
fatal: [management1]: FAILED! => changed=false
  failures:
  - No package openldap-servers available.
  - No package phpldapadmin available.
  msg: Failed to install some of the specified packages
  rc: 1
  results: []
```
From what I have read so far, it will never work on centos8 since openldap-servers does not seem to be disctributed anymore and for sure phpldapadmin does not exist as RPM on centos8.

So I suggest to fix the role by adding a task to check the OS and skipping if centos8 unless you provide a readme on how to build RPMs for Centos8 on those tools.

Any other suggestions?
Thanks!

**Comment by oxedions** [comment]
Dear @strus38 

Yes, this role was made during RHEL 7. You are right, thank you for notifying that 🙂 

It is still possible to find openldap rpms from external repositories, so I kept this role, but it would need some revamp to explain how to obtain them in the readme.

I was thinking adding IDM how to in the main documentation, since RedHat already provides all needed roles.

I will let this issue open so I remember to correct this (openldap and IDM).

**Comment by strus38** [comment]
I didn't even find any other repo having it!
Seems like no one wants to do it anymore 🤣

**Comment by oxedions** [comment]
You are right. All examples I find are build from sources. Strange no one added rpms into a repository 😐 
I never tried to build them, using rpmbuild. Did you try it ?

**Comment by strus38** [comment]
Nope, not yet, but I could give it a try. The next thing could be to maso
add the needed ldif files to easily deploy a test env. I  will check since
I need it for kerberos anyway.

**Comment by oxedions** [comment]
Ok, do not hesitate to keep me posted. I will have a look on my side either ;-)

**Comment by strus38** [comment]
I will have a look tomorrow... Not tonight ;-(

**Comment by strus38** [comment]
Ok, it seems like there is someone already doing it: https://ltb-project.org/documentation/openldap-rpm#yum_repository
So, I will try with that...
So in such case only the phpldapadmin part will be needed.

**Comment by btravouillon** [comment]
We should limit this role to RHEL7 only. Any solution with enterprise support will need the RPM from the OS vendor.

**Comment by strus38** [comment]
Agree, and the idm role from red hat is very good.

**Comment by oxedions** [comment]
Would this be enough for both of you ?
https://github.com/bluebanquise/bluebanquise/pull/471

**Comment by strus38** [comment]
For me we need:
- Free IPA (idm) solution to be updated to match BB (since not Working out
of the box)
- a solution for ldpa mgt GUI.

And so, yes we should limit the existing code on rhel7.

**Comment by oxedions** [comment]
Ok.
This is another topic, which need to be discussed.
I am closing this issue since the associated PR is merged. 🙂
