### ISSUE TITLE
Log_client: use ansible to set rsyslog default verbosity

### ISSUE THREAD

**Issue by DilasserT** [bluebanquise/bluebanquise#466]
Would it be appropriate to have ansible set the default verbosity in the log_client ?

Something like this:

`*.{{ log_client_verbosity }};mail.none;authpriv.none;cron.none                /var/log/messages`

instead of:

`*.info;mail.none;authpriv.none;cron.none                /var/log/messages`

**Comment by oxedions** [comment]
Dear @DilasserT 

Thank you for this issue.

You are right, it would be interesting to add this feature.

Would you accept to do the Pull Request ? This is not a major change.

1. You can add the `log_client_verbosity` variable in defaults of the role, and set it to info.
2. Add possibles values in the readme.
3. Increase the role version number (readme and vars).
4. Add a new entry in the main CHANGELOG.md

Could you do that ? 😊

**Comment by DilasserT** [comment]
Ok ! I'm working on it.

**Comment by oxedions** [comment]
I am closing this issue this PR has been merged. Thanks a lot for this contribution 🙂
