### ISSUE TITLE
[Multi-iceberg] Bug with pxe_stack role

### ISSUE THREAD

**Issue by Judunet** [bluebanquise/bluebanquise#482]
Hi, 

I have a problem when i want to deploy multi-iceberg with the pxe_stack role.
I have configured like in documentation a nfs share for /etc/bluebanquise but when i want to deploy new node in iceberg2 (for example) it will delete the iceberg3 configuration.

May be a solution to resolve that is to move the pxe directory from /etc/bluebanquise.

Regards

**Comment by oxedions** [comment]
Dear @Judunet 

Indeed, this is a bug in the design. I will think about that point, but clearly, the pxe folder should go somewhere else. It is probably time to create dedicated /etc folders for each tool (bootset and disklessset).

**Comment by oxedions** [comment]
see related #484

**Comment by oxedions** [comment]
Solved.
