### ISSUE TITLE
Nmcli need a patch

### ISSUE THREAD

**Issue by oxedions** [bluebanquise/bluebanquise#489]
Related to https://github.com/ansible-collections/community.general/pull/1260

We need this, to simplify the nmcli role. This issue is a reminder for this external PR.

**Comment by btravouillon** [comment]
https://github.com/ansible-collections/community.general/pull/1260 and https://github.com/ansible-collections/community.general/pull/1426 merged.
#504 uses these new features of the module nmcli.
