### ISSUE TITLE
Security issue in conman role

### ISSUE THREAD

**Issue by gavillom** [bluebanquise/bluebanquise#493]
Hi guys,

Through conman role, /etc/conman.conf is created in read mode for all users. That's to say users of a cluster can access to BMC credentials and manage server power control.

I think it would be better to change file rights to 600.

I can propose a PR for this.

Mathis

**Comment by btravouillon** [comment]
Indeed, default perms in the RPM are:
```
 -rw-------. 1 root root 10698 Aug 20 06:06 /etc/conman.conf
```

Waiting for your PR 😀

**Comment by gavillom** [comment]
#496
