### ISSUE TITLE
Diskless nodes and firewall

### ISSUE THREAD

**Issue by ginomcevoy** [bluebanquise/bluebanquise#495]
Diskless nodes created using the diskless role will have the firewall running by default. This can cause connectivity issues to services listening in compute nodes, that can only be reverted if disabling the firewall during image creation, or by running the "firewall" role or disabling it manually.

An initial mitigation can be to mention the firewall issue in the README of the diskless role.

**Comment by oxedions** [comment]
Dear @ginomcevoy 

Thanks a lot for this new issue.

I am wondering if, like for SELinux, we should not include that in the disklessset tool, with an entry like:

" Would you like to enable firewall inside image? (yes/no (default))"

Would that be ok for you ?

**Comment by ginomcevoy** [comment]
I think this would be a good idea, same treatment as for SELinux. 

Not sure how to best implement the feature in disklessset tool, but here is a suggestion. When the service is removed manually in a livenet image, these files are deleted:

```
[root@c002 ~]# systemctl disable firewalld
Removed /etc/systemd/system/multi-user.target.wants/firewalld.service.
Removed /etc/systemd/system/dbus-org.fedoraproject.FirewallD1.service.
```
So maybe deleting these two files from installroot while it is mounted is the way to go.

**Comment by btravouillon** [comment]
We had to do this for SELinux because we had no other way to restore the context of the files from the root filesystem.

For firewall, adding `ep_firewall: false` and the role `firewall` to the [customization playbook](https://bluebanquise.com/documentation/roles.html#customizing-livenet-image) is enough. We can add a note in the readme, but I don't think it worth to add a new interactive configuration to the disklessset tool.

**Comment by oxedions** [comment]
+1, I didn't remembered there was also the firewall service management in the `firewall` role. Then only to be documented.
@ginomcevoy Would you accept to do a PR to document that point ? 🙂

**Comment by ginomcevoy** [comment]
OK! I will create a PR later today.

**Comment by oxedions** [comment]
Thanks a lot 🙂 !

**Comment by oxedions** [comment]
PR is merged, closing this issue. Thanks a lot !
