### ISSUE TITLE
Wrong dhcp configuration for equipments with opt61

### ISSUE THREAD

**Issue by osmocl** [bluebanquise/bluebanquise#515]
**Description**

Hello guys, the advanced dhcp role is adding the `filename` configuration for all the equipments with opt61.

See here a wrong configuration for a switch. 
```
    host sw1-maint-net1-2 {
    option host-name "sw1-maint";
    option dhcp-client-identifier 00:50:66;
    fixed-address 192.160.0.4;
    filename "x86_64/standard_snponly_ipxe.efi";
```

I believe that the `filename` option should be present only for servers.

**Info**

Branch: stable-1.3
OS: rhel8.2

**Comment by oxedions** [comment]
Dear @osmocl 

Thank you for rising this issue.

Indeed, the role should not provide a filename if hosts is not with an equipment_profile of type server.

Would you accept to do a PR on master branch for core/dhcp_server and adv_core/adv_dhcp_server ? 🙂

**Comment by oxedions** [comment]
This issue is tranfered to new repository.
