### ISSUE TITLE
Cannot login or SSH after booting a livenet image with SELinux disabled

### ISSUE THREAD

**Issue by ginomcevoy** [bluebanquise/bluebanquise#521]
After creating a livenet image with SELinux disabled (Activate SELinux = no in disklessset), the image boots but cannot login.
SSH fails and logging in via the console prompt fails without error (it prompts for login again).

Reviewing the console shows these kernel parameters:
```
[    0.000000] Command line: initrd=initramfs-kernel-4.18.0-193.el8.x86_64 root=live:http://10.11.0.1/preboot_execution_environment/diskless/images/kitchen_image/squashfs.img rw console=tty0 console=ttyS1,115200n8 nomodeset  rd.net.timeout.carrier=30 rd.net.timeout.ifup=60 rd.net.dhcp.retry=4 selinux=False 
```

Manually setting `selinux=0` instead of `selinux=False` in
`/var/www/html/preboot_execution_environment/diskless/images/<image>/boot.ipxe` corrects the issue and login is possible.

**Comment by oxedions** [comment]
Dear @ginomcevoy 

Thanks a lot for rising this issue 🙂 

Would you accept to do a PR to fix the disklessset tool ?

Ox

**Comment by oxedions** [comment]
Closing since PR is merged.
