### ISSUE TITLE
sudo fails for diskless nodes with livenet image

### ISSUE THREAD

**Issue by ginomcevoy** [bluebanquise/bluebanquise#523]
sudo fails on nodes booting a livenet image:

```
[vagrant@c002 ~]$ sudo su
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
```

Inspection of the squashfs image shows that the setuid 's' attribute is missing:

```
[root@management1 diskless]# chroot /var/tmp/diskless/workdir/my_image/mnt
[root@management1 /]# ls -lah /usr/bin/sudo
---x--x--x. 1 root root 162K Feb  3 13:54 /usr/bin/sudo
```

Fix:
During image creation, the contents are copied using `cp -r` instead of `cp -a`, the fix is to correct the cp flag. I will propose a PR shortly.

**Comment by oxedions** [comment]
Dear @ginomcevoy 

Thanks a lot for rising this issue, and for the associated PR 🙂

**Comment by oxedions** [comment]
Closing since PR is merged.
