### ISSUE TITLE
Customization of livenet image using playbook with connection chroot fails to match host

### ISSUE THREAD

**Issue by ginomcevoy** [bluebanquise/bluebanquise#524]
When customizing a livenet image, the manual describes how to run a playbook using `connection: chroot` and the following hosts line:

```
hosts: /var/tmp/diskless/workdir/{{ image_name }}/mnt
```

This worked for the diskless manager in BlueBanquise release 1.3. However, for the new diskless manager, this fails to match the host:

```
[WARNING]: Could not match supplied host pattern, ignoring: /var/tmp/diskless/workdir/kitchen_image/mnt
```

This happens because a "/" has been added to the inventory file:

```
[root@management1 bluebanquise]# cat /var/tmp/diskless/workdir/kitchen_image/inventory/host
/var/tmp/diskless/workdir/kitchen_image/mnt/ ansible_connection=chroot
```

A PR will be proposed shortly to remove the extra '/' in the `host` inventory file.

**Comment by oxedions** [comment]
Dear @ginomcevoy 

Thanks a lot for rising this issue, and for the associated PR 🙂

**Comment by oxedions** [comment]
Closing since PR is merged.
