### ISSUE TITLE
diskless tool: dnf command "release version" argument stuck with selinux livenet images

### ISSUE THREAD

**Issue by pietersdavid** [bluebanquise/bluebanquise#528]
After testing the diskless tool with selinux i have discovered an issue with selinux.

When trying to create a livenet image with **selinux** and  **a release version** the dnf command is not working.

For exemple:

`DEBUG:dnf install dnf yum iproute procps-ng openssh-server NetworkManager selinux-policy-targeted selinux-policy-devel policycoreutils--releasever=8 -y --installroot=/var/tmp/diskless/workdir/livenet1/generated_os/ --setopt=module_platform_id=platform:el8
Unable to detect release version (use '--releasever' to specify release version)
`

We see that the command line is not set properly : **policycoreutils--releasever=8**.
That's generate an error during the generation.

**Comment by oxedions** [comment]
Solved. Closing.
