### ISSUE TITLE
roles pxe_stack and time is broken when using the skip-tags option

### ISSUE THREAD

**Issue by jpm38** [bluebanquise/bluebanquise#532]
There is a bug in bluebanquise roles pxe_stack and time.

pxe_stack/tasks/main.yml:

name: include_vars ░ Gather OS specific variables
include_vars: "{{ item }}"
with_first_found:

files:
"vars/{{ ansible_facts.distribution | replace(' ','') }}{{ ansible_facts.distribution_major_version }}.yml"
"vars/{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_major_version }}.yml"
"vars/{{ ansible_facts.distribution | replace(' ','_') }}.yml"
"vars/{{ ansible_facts.os_family }}.yml"
skip: true
tags:
firewall
internal
package
service
template

Some tags have been added to the task to allow (I suppose) these variables to be defined when executing pxe_stack role with some tags.

The problem is that when executing this role with a skip tag option to not execute package and service tasks. As a consequence, we do not include the needed variables and got an undefined variable.

**Comment by btravouillon** [comment]
Can you test with #535 and provide feedback?

**Comment by oxedions** [comment]
Would this solve this issue ?

In each task, include vars has tags:
```
- role_name_internal
- internal
```

And nothing else.

So if you need to play for example packages only, you use `internal,package`, or if you wish to restrict to this role only, `role_name_internal,package`.

?

**Comment by btravouillon** [comment]
Exposing a tag named `internal` to end-users is unexpected.

àla Puppet tags:
```
tags:
  - 'role::pxe_stack'
  - 'role::pxe_stack::skip'
```

Anyway I still believe tag `always` do the job for this task which has to be run when called from a playbook. Split your playbooks if you want to replay a subset of roles on a regular basis.

**Comment by oxedions** [comment]
I know.

But I still do not like this. I prefer the way it is today rather than using an always tag.

The only solution I found was to make variables "implicit" by using Jinja code (https://github.com/bluebanquise/bluebanquise/commit/3a06586c319da15f77df48fc02f0a29abf42fd61)

**Comment by oxedions** [comment]
Dear @jpm38 
Could you check please that your issue is solved with current master ?
