### ISSUE TITLE
Distro repositories are not properly disabled on new version of Centos

### ISSUE THREAD

**Issue by gavillom** [bluebanquise/bluebanquise#534]
Hi guys,

It feels like Centos 8 repositories are not properly disabled (with repositories_client_disable_distro_repos: true) with recent version of Centos.

It feels like repositories definition file name have been changed.

```
[root@gw yum.repos.d]# ll
total 48
-rw-r--r--. 1 root root  719 Nov 10 01:32 CentOS-Linux-AppStream.repo
-rw-r--r--. 1 root root  704 Nov 10 01:32 CentOS-Linux-BaseOS.repo
-rw-r--r--. 1 root root 1130 Nov 10 01:32 CentOS-Linux-ContinuousRelease.repo
-rw-r--r--. 1 root root  318 Nov 10 01:32 CentOS-Linux-Debuginfo.repo
-rw-r--r--. 1 root root  732 Nov 10 01:32 CentOS-Linux-Devel.repo
-rw-r--r--  1 root root  704 Feb 24 14:43 CentOS-Linux-Extras.repo
-rw-r--r--. 1 root root  719 Nov 10 01:32 CentOS-Linux-FastTrack.repo
-rw-r--r--. 1 root root  740 Nov 10 01:32 CentOS-Linux-HighAvailability.repo
-rw-r--r--. 1 root root  693 Nov 10 01:32 CentOS-Linux-Media.repo
-rw-r--r--. 1 root root  706 Nov 10 01:32 CentOS-Linux-Plus.repo
-rw-r--r--. 1 root root  724 Nov 10 01:32 CentOS-Linux-PowerTools.repo
-rw-r--r--. 1 root root  898 Nov 10 01:32 CentOS-Linux-Sources.repo
```

By default, _repositories_client_ role tries to remove a file named /etc/yum.repos.d/CentOS-Extras.repo (which is different than CentOS-Linux-Extras.repo).

Also BaseOS and AppStream file name has also been changed and so are still available when generating local repositories file.

I can propose a PR if you want.

Thanks

Mathis

**Comment by btravouillon** [comment]
Indeed, files were renamed: https://git.centos.org/rpms/centos-repos/c/b759b17557b9577e8ea156740af0249ab1a22d70?branch=c8

If you open a PR, it would be nice to make the code backward compatible with CentOS < 8.3.

**Comment by btravouillon** [comment]
CentOS made the change to prepare and ease the migration to Stream: https://wiki.centos.org/Manuals/ReleaseNotes/CentOS8.2011#Yum_repo_file_and_repoid_changes
