### ISSUE TITLE
powerman: when there is more than 300 equipments in a group the service cannot start

### ISSUE THREAD

**Issue by MarbolanGos** [bluebanquise/bluebanquise#548]
Hello,

In my case, I have a group containing all computes of my system (> 1000) and when this is generates the `/etc/powerman/powerman.conf` file, the server fails to start:
```
# systemctl status powerman
● powerman.service - PowerMan
   Loaded: loaded (/usr/lib/systemd/system/powerman.service; enabled; vendor preset: disabled)
   Active: failed (Result: core-dump) since Wed 2021-04-07 09:53:28 EEST; 27min ago
  Process: 62328 ExecStart=/usr/sbin/powermand (code=dumped, signal=SEGV)
 Main PID: 2883 (code=exited, status=1/FAILURE)

Apr 07 09:53:28 myhost systemd[1]: Starting PowerMan...
Apr 07 09:53:28 myhost systemd[1]: powerman.service: Control process exited, code=dumped status=11
Apr 07 09:53:28 myhost systemd[1]: powerman.service: Failed with result 'core-dump'.
Apr 07 09:53:28 myhost systemd[1]: Failed to start PowerMan.
```

After looking for the reason, it seems that if a line contains more than 300 nodes the server core dumps. What I have done is to split the group depending on the number of nodes within one rack:
```
include "/etc/powerman/ipmipower.dev"
# equipment_computes_BullSequana_XH2000 rack1
device "equipment_computes_BullSequana_XH2000" "ipmipower" "/usr/sbin/ipmipower " "/usr/sbin/ipmipower --wait-until-on --wait-until-off -h cn0001-ipmi,... -u ADMIN -p ADMIN |&"
node "cn0001,...""equipment_computes_BullSequana_XH2000" "cnXXXX-ipmi,..." 
[...]
# equipment_computes_BullSequana_XH2000 rackN
device "equipment_computes_BullSequana_XH2000" "ipmipower" "/usr/sbin/ipmipower " "/usr/sbin/ipmipower --wait-until-on --wait-until-off -h cnXXXX-ipmi,... -u ADMIN -p ADMIN |&"
node "cnXXXX,...""equipment_computes_BullSequana_XH2000" "cnXXXX-ipmi,..."
[...]
```

Is it possible to get a fix for this issue? I tried to do a loop depending on rack number to go over this but the time increased drastically for generating file...

**Comment by btravouillon** [comment]
Hi @MarbolanGos ,

Could you give a try to patch proposal in #549?
There is a new filter plugin which call ClusterShell.NodeSet to create a nodeset from a list of nodes. You need to install the python clustershell package on your Ansible Controller to make this work.

The powerman.conf file should look like:
```
device "equipment_typeC" "ipmipower" "/usr/sbin/ipmipower --wait-until-on --wait-until-off -h bc[001-004],node[0000-1000]-ipmi -u ADMIN -p ADMIN |&"
node "c[001-004],node[0000-1000]" "equipment_typeC" "bc[001-004],node[0000-1000]-ipmi"
```

**Comment by MarbolanGos** [comment]
Bruno, thank you for this patch. It worked perfectly! If patch is imported this issue is closed!

**Comment by btravouillon** [comment]
Let's keep it open until a fix merges.

**Comment by oxedions** [comment]
Was fixed with PR https://github.com/bluebanquise/bluebanquise/pull/596
