### ISSUE TITLE
ssh_master: host key mismatch log level

### ISSUE THREAD

**Issue by MarbolanGos** [bluebanquise/bluebanquise#557]
Hello,

In the case of diskless nodes, after every reboot, the `known_hosts` file is incorrect thus when logging in the node, there are some warning displays. This can be disturbing to get for each node such a warning.

In order to fix this, I have added this:
```
--- roles/core/ssh_master/templates/config.j2   2021-04-28 08:54:18.527323434 +0300
+++ roles/custom/ssh_master/templates/config.j2 2021-04-20 10:42:20.733492860 +0300
@@ -11,6 +11,7 @@ Host {{ host }}
           security.ssh.hostkey_checking == false %}
     StrictHostKeyChecking no
     UserKnownHostsFile=/dev/null
+    LogLevel QUIET
     {% endif %}
     {% if ssh_jump is none %}
     Hostname %h-{{ macro_node_main_network }}
```

What I wanted at the beggining was to be able to have security checkups still being active when being on a diskfull node and removing host checking when not being but I was not able to do it easily. 

This issue is a cosmetic issue but can help administrating the servers.

**Comment by oxedions** [comment]
Fixed in PR #648 😊
