### ISSUE TITLE
No documentation related to nfs_client_directories_state variable

### ISSUE THREAD

**Issue by gavillom** [bluebanquise/bluebanquise#594]
Hi all,

Would be glad to have a mention of nfs_client_directories_state variable into nfs_client documentation.
It's a very nice feature which is not spotlighted ;-)

Can help in doing it.

Thanks

Mathis

**Comment by oxedions** [comment]
Hello !

Thanks a lot for reporting this issue 🙂 

Does this PR comply with your request ?
https://github.com/bluebanquise/bluebanquise/pull/595/files

**Comment by gavillom** [comment]
Yes, it sounds good to me.

Thanks @oxedions

**Comment by oxedions** [comment]
Thanks for the feedback 😊
