### ISSUE TITLE
Update External Binaries

### ISSUE THREAD

**Issue by SckyzO** [bluebanquise/bluebanquise#626]
Hello Team. 

Do you think it is possible to update your externals binaries RPM ? 

| Program | Current Version | New Version |
|---|---|---|
| Prometheus | 2.19.2 | 2.30.3
| Alertmanager | 0.21.0 | 0.23.0 |
| Grafana | 6.7.4 | 8.0.3 |
| Karma | 0.68 | 0.92
| IPMI Exporter | 1.3.0 | 1.4.0
| Node Exporter | 1.0.1 | 1.2.2
| SNMP Exporter | 0.18.0 | 0.20.0 |

Regards,

**Comment by johnnykeats** [comment]
Hello @SckyzO 

Could you have a look here and tell us it matches your needs?

http://bluebanquise.com/repository/releases/1.5-dev/el8/x86_64/bluebanquise/packages/x86_64/

Beware, this is development repository, still haven't tested all the packages and not all are present.
Also, packages are for the new Prometheus role from @oxedions (https://github.com/bluebanquise/community/tree/main/roles/prometheus), which introduce a major (but mandatory) breaking change.

**Comment by SckyzO** [comment]
Perfect. I think I have all packages to testing :)

For the new role, I 've seen there are many changes. I can't upgrade my production currently, but I 'm very interested by your pipeline to improve packages releases cycle :) 
And, I think the best way for this stack is to use podman (only with centos/rh), and docker. But is not easy to use podman with node_exporter because podman is rootless. 

Thank you. I close the issue because I have all to testing update :)

**Comment by oxedions** [comment]
Dear @SckyzO 

Just a small note: these packages do not have services files anymore, as the new role generates them (I found that most of Prometheus eco-system tools parameters are passed as command line -> should be used indeed from a container). So to use them with the old role, you may wish to backup your current service files, and then only upgrade packages (and restore your services files if needed).

**Comment by SckyzO** [comment]
ok I take note. I keep you informed of the update
I use bluebanquise since one years so I used an old version ... 😁
But it's in production on customer site so I can't upgrade like this ☺️
And I already rewrite monitoring roles. Just I use bluebanquise for rpms. 

For information I use netapp eseries exporter, process exporter to help me to monitor architecture.  

Thank you for your help

Regards

**Comment by oxedions** [comment]
Welcome, and thanks for keeping us informed, it is always cool to have feedback 😊
