### ISSUE TITLE
[BUG] ssh_client role fails if network_interfaces is an empty list

### ISSUE THREAD

**Issue by ginomcevoy** [bluebanquise/bluebanquise#655]
## Context
When creating ansible inventory dynamically, it may happen that a host is defined with an empty list for network_interfaces. If this happens, the ssh_client role fails when executed on a management node of the same iceberg as the problematic host.

Since there is no explicit mention in the Bluebanquise data module about the impossibility of having an empty network_interfaces list, I have created this issue describing the problem and a possible solution.

## Process
Create an inventory entry like this one:
```
inventory/cluster/nodes/problematic.yml
mg_something:
  children:
    equipment_empty:
      hosts:
        emptyhost:
          network_interfaces: []
```

Notice that network_interfaces is an empty list, not just an empty variable (that does not fail).
Then run the ssh_client role in a management playbook:

```
ansible-playbook playbook/managements.yml --tags ssh_client
```
 
## Expected result
The role should succeed and behave as it network_interfaces had been empty for emptyhost: the file `/root/.ssh/config` should not have an entry for emptyhost, e.g.

```
#### Blue Banquise file ####
## Ansible managed file, do not edit

# Global parameters

Host c001
    Hostname %h-ice1-1

Host c002
    Hostname %h-ice1-1

Host management1
    Hostname %h-ice1-1
```

## Current result

The role fails with this error:

```
TASK [ssh_client : template █ Generate /root/.ssh/config] ****************************************************************
Friday 17 December 2021  02:37:12 +0100 (0:00:00.209)       0:00:24.281 *******
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: No first item, sequence was empty.
fatal: [management1]: FAILED! => changed=false
```

## Possible Fix

This fix seems to be enough to get the desired behavior:

```
diff --git a/roles/core/ssh_client/templates/config.j2 b/roles/core/ssh_client/templates/config.j2
index f03552a..ce9450b 100644
--- a/roles/core/ssh_client/templates/config.j2
+++ b/roles/core/ssh_client/templates/config.j2
@@ -58,7 +58,7 @@ Host *

 {% for host in (range | sort) %}
   {% set host_vars = hostvars[host] %}
-  {% if host_vars['network_interfaces'] is defined and host_vars['network_interfaces'] is iterable %}
+  {% if host_vars['network_interfaces'] | default([]) %}
 {{ write_host(host, host_vars, None) }}
   {% endif %}
 {% endfor %}
```

This will work for hosts that a) don't have network_interfaces (like internal), b) have empty network_interfaces, c) have network_interfaces as empty list, d) have network_interfaces as a populated list. The "if" will be true only for d). This test will fail if network_interfaces is something else like a dict.

`host_vars['network_interfaces'] is defined and host_vars['network_interfaces'] and host_vars['network_interfaces'] is iterable` also works, but I think this looks better.

I also experimented with other tests like "is not string" or "is not mapping" but they did not completely isolate the issue, I am waiting for a review of this before opening a PR. The fix was not "battle-tested" with a real-world inventory yet.

**Comment by johnnykeats** [comment]
Already encountered that one, but due to faulty inventory.

After reading your proposal: `host_vars['network_interfaces'] is defined and host_vars['network_interfaces']` is similar in logic. Maybe more text, but simpler to read.

If there is a need to cover all possibilities (aka users injecting dicts), the following line should secure all possibilities: `host_vars['network_interfaces'] is defined and host_vars['network_interfaces'] and host_vars['network_interfaces'] is not mapping`

**Comment by johnnykeats** [comment]
Please re-open issue if not closed by the patch merged.

**Comment by ginomcevoy** [comment]
Hello @johnnykeats , sorry for the delay.
The fix is working for me in a controlled environment, the problematic inventory is not causing the error anymore. Thank you!

I will test this on a more "real-like" scenario with a bigger inventory next week. If you don't hear from me it probably means the issue is gone :)
