### ISSUE TITLE
[BUG] - dns_server - dnssec-enable should be a variable to disable it if needed

### ISSUE THREAD

**Issue by strus38** [bluebanquise/bluebanquise#663]
DNS should be configurable to enable or disable dnssec-enable. A lot of setup don't need this feature.

This is done in:
- https://github.com/bluebanquise/bluebanquise/blob/master/roles/core/dns_server/templates/named.conf.j2
```
  dnssec-enable "{{ dns_server_role_dnssec-enable }}";
  dnssec-validation "{{ dnssec-validation  }}";
  dnssec-lookaside "{{ dnssec-lookasid }}";
```

Proposal is to simply add a variable in:

- https://github.com/bluebanquise/bluebanquise/blob/master/roles/core/dns_server/vars/main.yml
```
...
dns_server_role_dnssec-enable: true
dnssec-validation yes;
dnssec-lookaside auto;
...
```

**Comment by oxedions** [comment]
Feature was implemented. Closing issue. 🙂
