### ISSUE TITLE
[BUG] diskless - Unhelpful error message in "Create an image from a parameters file" if there are no kernels

### ISSUE THREAD

**Issue by ginomcevoy** [bluebanquise/bluebanquise#671]
This is a minor bug in disklessset tool, it does not impede functionality and is only about improving an error message.

## Context

I found this issue when I wanted to test the new "Create an image from a parameters file" functionality of the disklesset tool. I was starting from a "clean" system with no images and kernels present, so the tool was not ready because there are no kernels defined.

Still, the error message was not easily recognizable, I had to activate the traceback to understand the issue.

## Process

1. Start disklessset with no kernels added
2. Select option 5 "Create an image from a parameters file" 
3. Pass a correct image_data.yml file and confirm

## Expected result

A more informative error message related to not having kernels defined. Any of these could work:

```
[x] An exception occurred durring the installation process !
    The exception was: Invalid kernel parameter value

[-] No kernel available.

[-] No kernels found in /var/www/html/preboot_execution_environment/diskless/kernels/
    Please refer to readme.rst for details on how to obtain kernels.
```

## Current result

Got this error message:
```
[x] An exception occurred durring the installation process !
    The exception was: argument of type 'NoneType' is not iterable
```

## Possible Fix

This error is generated when checking if the kernel provided is among `KernelManager.get_available_kernels()`, but that function returns "None" if there are no kernels. Maybe return an empty list instead?

**Comment by oxedions** [comment]
Dear @ginomcevoy 

Sorry for the delay. I will have a look. 🙂

**Comment by oxedions** [comment]
PR https://github.com/bluebanquise/tools/pull/20/files

**Comment by oxedions** [comment]
@ginomcevoy Is the proposed PR ok for you ?

**Comment by ginomcevoy** [comment]
Hello @oxedions , looks good to me thanks!
