### ISSUE TITLE
[FEATURE REQUEST] add virtual ips to the cluster dns

### ISSUE THREAD

**Issue by strus38** [bluebanquise/bluebanquise#672]
Hi

Is there a way to add virtual ips to the cluster dns ?
 
Those ips in ./inventory/group_vars/all/general_settings/network.yml doesn’t seems to have any dns name resolution with the ha implementation  (something like nfs-vip or other names)  aka README on ha role
?
 
      dhcp_ip: 10.10.0.50
      pxe_ip: 10.10.0.51
      ntp_ip: 10.10.0.52
      nfs_ip: 10.10.0.53
      dns_ip: 10.10.0.54
      repository_ip: 10.10.0.55
      slurm_server_ip: 10.10.0.56
      time_ip: 10.10.0.57
      log_ip: 10.10.0.58
 
is it possible to implement this by default?
Thanks

**Comment by neilmunday** [comment]
I think this could be done but would would require adding something to map the IPs to DNS entries. E.g. "time-srv._domain_", "dhcp-srv._domain_" etc. The dns_server and advanced_dns_server roles would need modifying.

**Comment by oxedions** [comment]
Hello,

Yes, this is something we need to work on. I will do that just after @neilmunday  PR is merged 🙂

**Comment by oxedions** [comment]
Hello

What @neilmunday proposes is correct, and I would like to go this way. It however deeply change the inventory data model.
We need to delay this feature until 2.0.

I am adding tagging this PR to 2.0

**Comment by oxedions** [comment]
Updating this issue.
So right now, with BB 2.0, we have for each service possibility to define multiple entry, and ip + hostname.
Just need now to revert current precedence order (hostname should go first) and register these into hosts file and DNS

**Comment by oxedions** [comment]
Now fixed
