### ISSUE TITLE
make the role 'clustershell' idempotent?

### ISSUE THREAD

**Issue by sla31** [bluebanquise/bluebanquise#673]
Hi!

Wouldn't the following change help the role 'roles/core/clustershell' reach idempotence?
```
@@ -3,7 +3,7 @@
 
 {% for gr, gr_vars in groups.items() %}
 {% if (gr|string) != 'ungrouped' %}
-{{gr}}: {% for node in gr_vars %}{% if loop.first %}{{node}}{% else %},{{node}}{% endif %}{% endfor %}
+{{gr}}: {% for node in gr_vars | sort %}{% if loop.first %}{{node}}{% else %},{{node}}{% endif %}{% endfor %}
 
 {% endif %}
 {% endfor %}
```

Thanks!

**Comment by oxedions** [comment]
Dear @sla31 

My apologies for being so late. After 1.5 release, I took few days off 😊 
Yes, I agree. I already solved few idempotency on other roles recently, same issue.
Would you accept opening a PR with this path ?
