### ISSUE TITLE
[BUG] advanced_dhcp_server role fails on OpenSUSE

### ISSUE THREAD

**Issue by neilmunday** [bluebanquise/bluebanquise#696]
The `advanced_dhcp_server` role is missing SUSE vars files.

## Context

Example output:

```
TASK [advanced_dhcp_server : Package] ******************************************************************************************
Friday 15 April 2022  21:01:42 +0100 (0:00:00.164)       0:01:30.355 **********
fatal: [wolf0]: FAILED! =>
  msg: '''advanced_dhcp_server_packages_to_install'' is undefined'
```

## Process

Run the `advanced_dhcp_server` role on a SLES based OS (e.g. OpenSUSE 15.3)

## Expected result

The role executes without error.

## Current result

See output above.

## Possible Fix

Will create a pull request with a fix shortly.

**Comment by oxedions** [comment]
Closing since PR was merged. Thanks for the devs 😊
