### ISSUE TITLE
force installation on a specific interface name

### ISSUE THREAD

**Issue by sla31** [bluebanquise/bluebanquise#720]
Hi!

Installing a server with 2 network interfaces teamed in an LACP bond.  Installing the server through only one of both interfaces is fine; the bond is useful only after OS installation.  The inventory defines 2 network interfaces + the bond interface as follows:
```
- interface: bond0
  ip4: 172.31.255.2
  network: admin1-1
  type: bond
  vlan: false
  bond_options: "mode=4 xmit_hash_policy=layer3+4 miimon=100 lacp_rate=fast"
  mac: 10:70:fd:33:2e:72
- interface: enp65s0f0np0
  type: bond-slave
  master: bond0
- interface: enp65s0f1np1
  type: bond-slave
  master: bond0
```

As the "initrd" fails to bring the proper network up to download the netboot ISO, I need to force the network config on the kernel command line with the following command:
```
bootset -n MY_SERVER -b osdeploy --force network
```

But then, the interface name which is used on the kernel command line is "bond0" instead of the name of individual interface used for OS installation.

What's worse in my case is:

- the final interface name will be "enp65s0f0**np0**" as described in the inventory (with the up-to-date Mellanox driver for that network interface)
- but the interface name during installation is "enp65s0f0" (because the "initramfs" does not have the same/latest version of the `mlx5_core` Mellanox driver)

It'd be nice if we could specify somewhere the name of the interface used for OS installation when forcing the network config on the kernel command line with `bootset`!

Thanks a lot!

**Comment by oxedions** [comment]
Dear @sla31 

Thanks a lot for reporting this issue. 😊 
It makes sens, let me add it to backlog for devs.
