### ISSUE TITLE
make the gateway optional when forcing static network config on the kernel command line with bootset

### ISSUE THREAD

**Issue by sla31** [bluebanquise/bluebanquise#721]
Hi!

Partly related to enhancement request #720.

I need to force the network config statically on the kernel command line with the following command:
```
bootset -n MY_SERVER -b osdeploy --force network
```
But the network used for OS installation has no gateway:

- the OS gets installed through an interface on a closed network (internal to the cluster)
- the server will be connected to a DMZ through another network interface (that's where the default gateway will be)

It'd be nice if we could force a static network config on the kernel command for OS installation purposes (`bootset --force network`) without being forced to define a (dummy) gateway on the installation network.

Thanks!

**Comment by oxedions** [comment]
Dear @sla31 

Yes, I understand, it also make sens.
I will fix that at the same time than the other issue reported 🙂
