### ISSUE TITLE
[FEATURE REQUEST] sos_report script to understand issues

### ISSUE THREAD

**Issue by strus38** [bluebanquise/bluebanquise#727]
[Provide general introduction to the feature request, and why it is relevant to this repository]

## Context

sos-report are used for many software to get a dump of a config used by a customer and provide the necessay information for the support to understand what could be the issue.

## Feature

The feature is about creating such script which could be used to better understand issues happening in the field.
Such content could be:
- RPM list
- os release
- BB inventory anonymised (IP/MAC/secrets)
- network info (anonymised)
- roles  list and version (extract from roles/vars/main.yml)
- etc...

**Comment by neilmunday** [comment]
I think the name of the script should avoid clashing with RHEL's `sosreport` tool. Perhaps `bb-sos`?

**Comment by strus38** [comment]
Well, the name of the script, I don't mind :-) ...

**Comment by btravouillon** [comment]
That should be a [plugin for sos report](https://github.com/sosreport/sos/wiki/How-to-Write-a-Plugin) IMHO.

**Comment by oxedions** [comment]
Hello.

Yes, using sosreport is the way to go.

However, implementing a plugin for BB data is a huge dev, that I cannot afford right now... 😞 
In the meantime, you can easily grab BB data by creating a tar of bluebanquise folder. I know it will not be anonymized, but user can use sed commands to empty/NA needed yaml keys in all files.

**Comment by strus38** [comment]
I will work on it.

**Comment by oxedions** [comment]
Thanks a lot ! 😀

**Comment by strus38** [comment]
The proposed implementation could be the following:

- Create a command line smc-report
- The command line would be an alias on an ansible-playbook which would perform the following operations:
    - get all the nodes of the cluster through the inventory
    - perform a standard sosreport on the node (the sosreport cli sems to be supported on all platforms) - this gives all pertinent data + containers information
    - gather specific BB files like: BB release, inventory, playbooks, roles, custom_roles
    - gather HA data when available

@oxedions do you think it is enough?

Thanks.

**Comment by btravouillon** [comment]
To my knowledge sosreport can collect data about HA configuration and status. This might not be the default though. (I believe the tool is smart enough to detect if pcs/corosync are installed and collect data accordingly)

Collecting BB data with a module for sos would help because one would end with a single report package to send to their support representative. Your support team should be happy as well to find all the required information in a single place. Just sayin' 😃
