### ISSUE TITLE
[BUG] bootstrap.sh offline installation.

### ISSUE THREAD

**Issue by santos-lucas** [bluebanquise/bluebanquise#730]
[Provide general introduction to the issue logging and why it is relevant to this repository.]

On the offline installation, the requirements.txt when offline download seems to not be downloading all the requirements dependencies, what creates some erros on the bootstrap script installation on offline_mode.

╔══════════════════════════════════════════════╗
 ║ Installing python needed dependencies via pip3...
 ╚══════════════════════════════════════════════╝
Defaulting to user installation because normal site-packages is not writeable
Looking in links: /home/bluebanquise/bluebanquise/offline_bootstrap/pip3/
Requirement already satisfied: pip in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (21.3.1)
Processing ./offline_bootstrap/pip3/ansible-4.10.0.tar.gz
  Preparing metadata (setup.py) ... done
Processing ./offline_bootstrap/pip3/netaddr-0.8.0-py2.py3-none-any.whl
Processing ./offline_bootstrap/pip3/ClusterShell-1.8.4.tar.gz
  Preparing metadata (setup.py) ... done
Processing ./offline_bootstrap/pip3/jmespath-0.10.0-py2.py3-none-any.whl
Processing ./offline_bootstrap/pip3/ansible-core-2.11.12.tar.gz
  Preparing metadata (setup.py) ... done
Processing ./offline_bootstrap/pip3/importlib_resources-5.4.0-py3-none-any.whl
Processing ./offline_bootstrap/pip3/PyYAML-6.0.tar.gz
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.6 /usr/local/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-mcsz_02a/overlay --no-warn-script-location --no-binary :none: --only-binary :none: --no-index --find-links /home/bluebanquise/bluebanquise/offline_bootstrap/pip3/ -- setuptools wheel Cython
       cwd: None
  Complete output (3 lines):
  Looking in links: /home/bluebanquise/bluebanquise/offline_bootstrap/pip3/
  ERROR: Could not find a version that satisfies the requirement setuptools (from versions: none)
  ERROR: No matching distribution found for setuptools
  ----------------------------------------
WARNING: Discarding file:///home/bluebanquise/bluebanquise/offline_bootstrap/pip3/PyYAML-6.0.tar.gz. Command errored out with exit status 1: /usr/bin/python3.6 /usr/local/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-mcsz_02a/overlay --no-warn-script-location --no-binary :none: --only-binary :none: --no-index --find-links /home/bluebanquise/bluebanquise/offline_bootstrap/pip3/ -- setuptools wheel Cython Check the logs for full command output.
INFO: pip is looking at multiple versions of netaddr to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of ansible to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pip to determine which version is compatible with other requirements. This could take a while.
Processing ./offline_bootstrap/pip3/pip-21.3.1-py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement PyYAML (from clustershell) (from versions: 6.0)
ERROR: No matching distribution found for PyYAML

[Provide more detailed introduction to the issue context.]

Os is RedHat 8.5 and it was installed as minimal install.

**Comment by oxedions** [comment]
Dear @santos-lucas 

Interesting, thanks a lot for catching this. I will setup a VM and investigate 🙂

**Comment by oxedions** [comment]
Should be solved now :blush: 
Closing.
