### ISSUE TITLE
[BUG] bootstrap on bluebanquise release poiting to latest repo

### ISSUE THREAD

**Issue by santos-lucas** [bluebanquise/bluebanquise#735]
The bootstrap.sh script on release 1.6 is using the latest version of the bluebanquise repositories and some packages like disklessset are outdated there. 

we probably should fix the repo version on the release.

**Comment by oxedions** [comment]
Dear @santos-lucas 

Thanks for reporting that !

Yes, repositories need to be updated. I am in the process of automating all of that, I hope it will be done soon.
I will update latest as soon as possible 😊

**Comment by oxedions** [comment]
Hello @santos-lucas 
New script should be more efficient now.
However, I wonder how to make it bind to the correct version when doing a release 😐

**Comment by santos-lucas** [comment]
Great, I will take a look into it too

**Comment by oxedions** [comment]
Dear @santos-lucas 

Did you had time to investigate the script ? :blush:

**Comment by oxedions** [comment]
I think this issue can be closed now, considering BB 3 and the fact that it only uses the latest release. Please re-open this issue if this does not suit your needs :blush:
