### ISSUE TITLE
[FEATURE REQUEST] Logrotate configuration for conman

### ISSUE THREAD

**Issue by dietergorecki** [bluebanquise/bluebanquise#754]
No logrotate configuration is provided for conman.

## Feature

A file dedicated to conman log rotation in /etc/logrotate.d/ would do the trick.

## Additional data

Example configuration file:

```
$ cat /etc/logrotated.d/conman
/var/log/conman/*.log {
  compress
  dateext
  missingok
  nocopytruncate
  nocreate
  nodelaycompress
  nomail
  rotate 4
  sharedscripts
  weekly
  postrotate
    /usr/bin/killall -HUP conmand
  endscript
}

```

**Comment by oxedions** [comment]
Dear @dietergorecki 

Apologies for being so late. I was moving to another country with family, it was hard for me to keep up.

Your request make sens, I will try to ad it asap 😊

**Comment by oxedions** [comment]
Feature have been implemented by @strus38
