### ISSUE TITLE
[BUG] rsyslog - server not writing locally, apps logs not being fowarded

### ISSUE THREAD

**Issue by thiagocardozo** [bluebanquise/bluebanquise#768]
## Context

1.  Server has all templates with _/var/log/rsyslog/%HOSTNAME%/*\_, which means that all it`s logs are in the rsyslog subfolder.
Many users will expect these logs to also be in their standard location _/var/log/*_.
We can devise some symlinks, but I prefer to add filter to also add those logs locally in the same way is done with clients.

2. The rule for remote applications logs was removed a few versions ago, therefore they are not present in rsyslog subfolder.
For this we can just add the rule back.

3. The logrotation rule is too wide and tries to rotate already rotated logs.

**Comment by oxedions** [comment]
@thiagocardozo can we close the issue since PR is merged ? 🙂

**Comment by thiagocardozo** [comment]
Closed since PR was merged. :)
