### ISSUE TITLE
PXE with VLAN

### ISSUE THREAD

**Issue by GaelBil** [bluebanquise/bluebanquise#831]
## Context

In many cluster we want (or have to) setup different VLAN for server and their BMC.
In case of shared port for BMC and server the current situation is quite complex to deal with.

To explain the situation I will give an example.
My VLAN ID are:

- 10 for server
- 20 for BMC

My management servers have an interface on each VLAN.
The default VLAN is not permitted.

In the current situation I have to configure my switch to tag the VLAN 10 by default and to permit the transport of the VLAN 20 (trunk).
This way, when my server will boot, its DHCP request will be tag with the VLAN 10 and it will be able to perform a PXE / iPXE boot (or install).
The problem with this method is that I cannot access my BMC. The obvious workaround is to use a range of IP for a DHCP to get a temporary IP for the BMC, then set the VLAN directly on the BMC. For that you may need to declare your BMC twice in your inventory.

## How to

It is possible to simplify the process by changing fie things.

### SWITCH

First you have to configure your switch to tag the VLAN 20 by default. This way you will be able to access your BMC easily without a temporary IP.

### PXE

Obviously in this situation, your server will not be able to get an IP address (because DHCP request go through the VLAN 20).
So you need to configure the VLAN 10 directly in the BIOS through the BMC.
You can use different tools depending on the brand of your server :

- redfish
- gbtutility (for gigabyte)
- onecli (for lenovo)
- ...

After that, your server will be able to performe a PXE.

### iPXE

Now that you are able to perform a PXE, you need to recompile your iPXE binary with the VLAN support enabled.

```
git clone git://git.ipxe.org/ipxe.git
cd ipxe/src
sed -i 's///#define VLAN_CMD/#define VLAN_CMD/' config/general.h
```

Create a small iPXE script
```
cat myscript.ipxe
#!ipxe

vcreate --tag 10 net0

:rdhcp
dhcp net0-123&& goto rboot || goto rdhcp

:rboot
chain http://<managementserverIP>/preboot_execution_environment/convergence.ipxe || goto rboot
```
Then recompile you iPXE binary
```
make bin/undionly.kpxe EMBED=myscript.ipxe
```

To be sure that your server download this binary, I add a variable in the equipment_profile:
```
[...]
ipxe_filename: "x86_64/ipxe.efi"
[...]
```
And I changed the role *advanced_dhcp_server*

```
cat roles/advanced_core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2
[...]
    {% if current_hostvars['ipxe_filename'] is defined %}
      {% set ipxe_rom_filename = current_hostvars['ipxe_filename'] %}
    {% endif -%}
[...]
```

### Osdeploy

If you perform **osdeploy** operation, you need to add the vlan definition in your equipment profile ipxe file.
```
cat /var/www/html/preboot_execution_environment/equipment_profiles/<your_profile>
[...]
set eq-kernel-parameters crashkernel=512M intel_pstate=disable nosmap numa_balancing=disable ipmi_si.force_kipmid=0 transparent_hugepage=never nmi_watchdog=0 iommu=pt selinux=0 mitigations=off vlan=eno1.10:eno1
[...]
```
You also need to change your kickstart.
I added a new variable in my equipement profile
```
[...]
ks_vlan: 10
[...]
```
And I updated a template to use this variable
```
cat roles/core/pxe_stack/templates/RedHat/kickstart.cfg.j2
[...]
{% if hostvars[groups[item][0]]['ks_vlan'] is defined %}
network --bootproto=dhcp --ipv6=auto --activate --vlanid {{ hostvars[groups[item][0]]['ks_vlan'] }}
{% else %}
network --bootproto=dhcp --ipv6=auto --activate
{% endif %}
network --hostname=localhost.localdomain
[...]
```

## Feature

Add all those step to the currect stack.

**Comment by oxedions** [comment]
Dear @GaelBil 

Sorry for the delay.
Many thanks ! 😊  I will try to add documentation on that specific part asap !

**Comment by oxedions** [comment]
Documentation added into main doc. Closing now, thanks a lot ! :blush:

**Comment by samgrcia** [comment]
Hello, there is a mistake in a sed expression in the doc [6.1.1. VLAN PXE boot](http://bluebanquise.com/documentation/advanced_usage.html#vlan-pxe-boot):

```
sed -i 's///#define VLAN_CMD/#define VLAN_CMD/' config/general.h
```

Should be : 

```
sed -i 's/\/\/#define VLAN_CMD/#define VLAN_CMD/' config/general.h
```

The backslashes are missing 😄
