### ISSUE TITLE
BB-12 -  [BUG] NFS firewall rule missing mountd for Redhat and related distros

### ISSUE THREAD

**Issue by sgaosdgr** [bluebanquise/bluebanquise#852]
NFS role only opens two services nfs and rpc-bind for firewall rule.  With only this two services opened, an NFS client can not mount or run showmount successfully. 

Another issue is that the variable, nfs_server_firewall_services_to_add, is not recognized when set in playbook.  

## Context

Current setting in collections/file_systems/roles/nfs/vars/RedHat.yml:

`nfs_server_firewall_services_to_add:
  - nfs
  - rpc-bind`

mountd should be added as shown below:

`nfs_server_firewall_services_to_add:
  - mountd
  - nfs
  - rpc-bind`
  
## Process

To reproduce the issue:

On a mgt node:
1. Clone the master branch
2. Install collection 'file_systems'
3. On mgt node, create a directory, /export/apps.  Set nfs to export /export/apps. Run this playbook against mgt node:
`ansible-playbook playbooks/managements.yml -i inventory --extra-vars "@bluebanquise_core.yml" --limit mgt1 --tags nfs`
4. Run this playbook against a compute node:
`ansible-playbook playbooks/computes.yml -i inventory --extra-vars "@bluebanquise_core.yml" --limit compute1  --tags nfs`
5. On compute1, run `showmount -e mgt1` or run `mount -t nfs mgt1:/export/apps /share/apps`

## Expected result

On node compute1, /export/apps from mgt1 should be mounted successfully as /share/apps.

The command `showmount -e mgt1` should return following result:
`$ showmount -e mgt1
Export list for mgt1:
/export/apps 192.168.1.0/24`

## Current result

1. /export/apps failed to be mounted on compute1 under /share/apps
2. Command `showmount -e mgt1` returned no route error

## Possible Fix

Add 'mountd' to firewall rule for NFS by modifying collections/file_systems/roles/nfs/vars/RedHat.yml as below:

`..........
nfs_server_firewall_services_to_add:
  - mountd
  - nfs
  - rpc-bind`

## Additional data

OS: RockyLinux 9.3 x86_64 with latest updates

**Comment by oxedions** [comment]
Dear @sgaosdgr 

Many thanks for reporting this issue! :blush: 
Indeed, I can read inside RedHat documentation that this service should be added. I only tested mounts locally or using NFS v4.2, so I missed the firewall and NFSv3 tests this way. Apologies for this, I have to improve testings.

I will do few testings and come back to you, because I can see lockd and statd are also required in some cases to provide a full NFS support. This might also explain the current issue I also have with the diskless tool.

Please give me few days to investigate and patch this :slightly_smiling_face:

**Comment by oxedions** [comment]
First iteration of tests:

Indeed, when I deploy a basic example:

```yaml
nfs_shares:
  - export: /opt/software
    server: mgt3
    mount: /opt/software
    clients_groups:
      - fn_management
    network: net-admin
    export_options: rw,async
    mount_options: rw,nfsvers=4.2,bg
```

If I want to mount it over nfsv4, it works, but if I try with nfsv3, it hangs:

```
(ansible_venv) bluebanquise@mgt1:~/validation$ sudo mount -t nfs mgt3:/opt/software /toto -o nfsvers=4
(ansible_venv) bluebanquise@mgt1:~/validation$ sudo df -h
Filesystem                         Size  Used Avail Use% Mounted on
tmpfs                              786M  1.3M  785M   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv   22G  7.5G   14G  37% /
tmpfs                              3.7G     0  3.7G   0% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
/dev/vda2                          2.0G  129M  1.7G   8% /boot
tmpfs                              678M  4.0K  678M   1% /run/user/1001
mgt3:/opt/software                 7.8G  3.5G  4.0G  47% /toto
(ansible_venv) bluebanquise@mgt1:~/validation$ sudo umount /toto

(ansible_venv) bluebanquise@mgt1:~/validation$ sudo mount -t nfs mgt3:/opt/software /toto -o nfsvers=3
^C  # <<< Here I Ctrl+C after 30s hang
(ansible_venv) bluebanquise@mgt1:~/validation$
```

And I cannot showmount:

```
(ansible_venv) bluebanquise@mgt1:~/validation$ sudo showmount -e mgt3
rpc mount export: RPC: Unable to receive; errno = No route to host
(ansible_venv) bluebanquise@mgt1:~/validation$
```

Solution is indeed to add mountd to services list:

```
ansible-playbook playbooks/managements.yml -b --limit mgt3 -i inventories/minimal_extended/ -e nfs_server_firewall_services_to_add="['nfs','mountd','rpc-bind']" -e os_firewall=true
```

Which shows in firewall configuration:

```
[bluebanquise@mgt3 ~]$ sudo firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp1s0
  sources: 
  services: cockpit dhcpv6-client http mountd nfs rpc-bind ssh
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
[bluebanquise@mgt3 ~]$ 
```

And then it can work with showmount and nfsv3:

```
(ansible_venv) bluebanquise@mgt1:~/validation$ sudo showmount -e mgt3
Export list for mgt3:
/opt/software 10.10.0.0/16
(ansible_venv) bluebanquise@mgt1:~/validation$ sudo mount -t nfs mgt3:/opt/software /toto -o nfsvers=3
(ansible_venv) bluebanquise@mgt1:~/validation$ df -h
Filesystem                         Size  Used Avail Use% Mounted on
tmpfs                              786M  1.3M  785M   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv   22G  7.5G   14G  37% /
tmpfs                              3.7G     0  3.7G   0% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
/dev/vda2                          2.0G  129M  1.7G   8% /boot
tmpfs                              678M  4.0K  678M   1% /run/user/1001
mgt3:/opt/software                 7.8G  3.5G  4.0G  47% /toto
(ansible_venv) bluebanquise@mgt1:~/validation$ sudo umount /toto
(ansible_venv) bluebanquise@mgt1:~/validation$ 
```

I will add a fix once I have checked with the other distributions (Ubuntu, Debian and Sles).

Note that the `nfs_server_firewall_services_to_add` works, but it is defined as a vars loaded using an include_vars inside the role.
(This : https://github.com/bluebanquise/bluebanquise/blob/4ac40018de41d096328f6e56b05b45e07ea8faca/collections/file_systems/roles/nfs/tasks/main.yml#L2 loads that : https://github.com/bluebanquise/bluebanquise/blob/master/collections/file_systems/roles/nfs/vars/RedHat.yml).

So in the Ansible precedence mechanism, it is nearly a top variable (see https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#understanding-variable-precedence). Best solution to overlap that kind of "winning" variables is to use extra-vars at ansible-playbook command, as it always precedence all.
So here, I added `-e nfs_server_firewall_services_to_add="['nfs','mountd','rpc-bind']"`. You need to use Json format here (this is what would be in an INI ansible inventory file).

I will provide a fix asap once I have check with the other OS :blush:

**Comment by sgaosdgr** [comment]
Thanks for very quick response and explanation. 

In this case, include_vars basically restricts where the nfs role will get its variables for a particular OS, therefore ignores the same variable set in a playbook.  But extra-vars overrides not matter what.

**Comment by sgaosdgr** [comment]
Saw the same issue with collections/infrastructure/roles/pxe_stack/vars/RedHat_9.yml

```
pxe_stack_diskless_firewall_services_to_add:
    - nfs
    - rpc-bind
```

**Comment by oxedions** [comment]
Sorry for the delay of my answers, I do all of that on my free time and with kids some days its not easy to find time :blush: 

Yes, you got it. In Ansible roles, vars are here for the internal logic of the role, and so are not expected to be overwritten by users (except using extra vars or facts), and defaults are here for the external logic of the role, aka what is expected to be modified by the users to adapt the role to his/her needs using inventory.


Good catch for the pxe_stack role, NFS is used for diskless golden creation too. I will fix it :wink:

**Comment by oxedions** [comment]
PR is opened, could you check its ok for you ? https://github.com/bluebanquise/bluebanquise/pull/856
Thanks a lot! :blush:
