### ISSUE TITLE
BB-13 - [BUG] role repositories adds an extra space to the base url

### ISSUE THREAD

**Issue by toto-xoxo** [bluebanquise/bluebanquise#857]
The repositories role adds an extra space to the base url, making the repo invalid. Example below where there is an extra space before AppStream. The problem occurs with all repos configured with bb_repositories.

## Context

bb_repositories settings :

```
bb_repositories:
  - BaseOS
  - AppStream
  - epel
  - bluebanquise
```

## Process

Execute repositories role

`ansible-playbook playbooks/managements.yml -i inventory --limit management1 --tags=repositories -b`

## Expected result

```
[AppStream]
baseurl =  http://10.10.0.1/repositories//redhat/9.2/x86_64/AppStream/
enabled = 1
gpgcheck = 0
name = AppStream gen by Ansible
```

## Current result

```
[AppStream]
baseurl =  http://10.10.0.1/repositories//redhat/9.2/x86_64/ AppStream/
enabled = 1
gpgcheck = 0
name = AppStream gen by Ansible
```

**Comment by oxedions** [comment]
Dear @toto-xoxo 

Many thanks for this bug report ! :blush: 
Indeed, this is a nasty bug. I will propose a fix.

**Comment by oxedions** [comment]
Dear @toto-xoxo 
Could you please check https://github.com/bluebanquise/bluebanquise/pull/859 and confirm me it fixes the issue ? :slightly_smiling_face:

**Comment by toto-xoxo** [comment]
> Dear @toto-xoxo Could you please check #859 and confirm me it fixes the issue ? 🙂

Hey @oxedions , thanks for the fix. I confirm this is working 👍
