### ISSUE TITLE
BB-21 - [FEATURE REQUEST] Install OS on specified disk only

### ISSUE THREAD

**Issue by sgaosdgr** [bluebanquise/bluebanquise#868]
When not specifying which disk to install OS, OS installation can use all disks found on a system.  For a machine with two or more disks, installation only use the specified disk (normally the first disk) is important since the other disks may be dedicated for database, or other applications. 

OS environment: RockyLinux 9.3 x86_64

Here is one example of two disks on a system before specifying OS installation on first disk.  The OS was installed using both disks and main OS packages were installed on the second disk.  The example is produced with BB 2.x. 

```
Filesystem                     Size  Used Avail Use% Mounted on
devtmpfs                       4.0M     0  4.0M   0% /dev
tmpfs                           16G     0   16G   0% /dev/shm
tmpfs                          6.2G   22M  6.2G   1% /run
/dev/nvme1n1p3                 1.8T   14G  1.8T   1% /
/dev/nvme1n1p2                 836M  206M  631M  25% /boot
/dev/nvme0n1p1                  60G  703M   60G   2% /var
/dev/nvme1n1p1                 500M  7.0M  493M   2% /boot/efi
tmpfs                          3.1G  4.0K  3.1G   1% /run/user/1000
```

lsblk:
```
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
nvme0n1     259:0    0 476.9G  0 disk 
├─nvme0n1p1 259:1    0    60G  0 part /var
└─nvme0n1p2 259:2    0    16G  0 part [SWAP]
nvme1n1     259:3    0   1.7T  0 disk 
├─nvme1n1p1 259:4    0   500M  0 part /boot/efi
├─nvme1n1p2 259:5    0   900M  0 part /boot
└─nvme1n1p3 259:6    0   1.7T  0 part /
```

After specifying first found disk only, ie nvme0n1, the OS installation only used nvme0n1:
```
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        4.0M     0  4.0M   0% /dev
tmpfs            16G     0   16G   0% /dev/shm
tmpfs           6.2G   13M  6.2G   1% /run
/dev/nvme0n1p5  1.7T   13G  1.7T   1% /
/dev/nvme0n1p2  2.0G  214M  1.8G  11% /boot
/dev/nvme0n1p3   60G  540M   60G   1% /var
/dev/nvme0n1p1  500M  7.0M  493M   2% /boot/efi
tmpfs           3.1G     0  3.1G   0% /run/user/1000
```

## Context

This issue is found with BB 2.x releases.  It can happen to BB 3.x release as well.

## Feature

To specify a disk for OS installation:

1. Add a new variable, ep_boot_disk, BB-2; os_boot_disk for BB-3, in group vars, equipment profile or os profile

For example for BB-2, add following lines to: inventory/group_vars/all/equipment_all/equipment_profile.yml
```
ep_boot_disk: nvme0n1 

ep_partitioning: |
  ignoredisk --only-use={{ ep_boot_disk }}
  clearpart --drives={{ ep_boot_disk }} --all --initlabel
  part /boot/efi --fstype=efi --size=500 --ondisk={{ ep_boot_disk }}
  part /boot --fstype=xfs --size=2048 --ondisk={{ ep_boot_disk }}
  part swap --fstype=swap --size=16384 --ondisk={{ ep_boot_disk }}
  part /var --fstype=xfs --size=61440 --ondisk={{ ep_boot_disk }}
  part / --fstype=xfs --size=4096 --grow --ondisk={{ ep_boot_disk }}
```

For example for BB-3: add following lines to: inventory/group_vars/os_rockylinux_9/settings.yml:
```
os_boot_disk: nvme0n1 

os_partitioning:
  ignoredisk --only-use={{ os_boot_disk }}
  clearpart --drives={{ os_boot_disk }} --all --initlabel
  autopart --type=plain -fstype=ext4 --ondisk={{ os_boot_disk }}
```

3. The result would be like:
``` 
...
# Partitioning
ignoredisk --only-use=nvme0n1
clearpart --drives=nvme0n1 --all --initlabel
part /boot/efi --fstype=efi --size=500 --ondisk=nvme0n1
part /boot --fstype=xfs --size=2048 --ondisk=nvme0n1
part swap --fstype=swap --size=16384 --ondisk=nvme0n1
part /var --fstype=xfs --size=61440 --ondisk=nvme0n1
part / --fstype=xfs --size=4096 --grow --ondisk=nvme0n1
```

Or 
```
# Partitioning
ignoredisk --only-use=nvme0n1
clearpart --drives=nvme0n1 --all --initlabel
autopart --type=plain --fstype=ext4 --ondisk=nvme0n1
```

## Additional data

Manually setting, ep_boot_disk or os_boot_disk, is one step to improve.  The more complete solution is adding a check/find to kickstart config file to probe and set first disk on the fly during installation.

Here is the example about finding the 1st disk whether it's nvme0n1 or sda:

```
%include /tmp/partitions

%pre
DIR="/sys/block"
ROOTDRIVE=""

if [ -L $DIR/nvme0n1 ]; then
   ROOTDRIVE="nvme0n1"
else
   ROOTDRIVE="sda"
fi

cat >> /tmp/partitions << EOF
bootloader --append="net.ifnames=0 crashkernel=auto" --location=mbr --boot-drive=${ROOTDRIVE}
clearpart --drives=${ROOTDRIVE},${SCRDRIVE} --all --initlabel
part / --fstype=xfs --asprimary --size=2048 --grow --ondisk=${ROOTDRIVE}
EOF
%end
...
```

**Comment by oxedions** [comment]
Dear @sgaosdgr 

Thank you very much for this feature request :blush: 
This is an interesting request. Please give me few hours to compute that, I lack coffee today so I need more time than usual :slightly_smiling_face:

**Comment by oxedions** [comment]
Dear @sgaosdgr 

For clarification: since you can currently use the os_partitioning (or ep_partitioning in BB 2) to set disk name by providing raw kickstart code, your idea here is to be able to use the automated partitioning provided by the stack but be able to specify the disk, do I get it right ? :slightly_smiling_face:

**Comment by sgaosdgr** [comment]
In either case (auto partitioning or manual partitioning), it's very helpful to set a variable "os_boot_disk" to give users a choice. I did not try auto partitioning and not sure auto partitioning would only use one disk for OS installation. 

Here is what can be done:

If `os_boot_disk` is not null, then 

```
os_partitioning: |
  ignoredisk --only-use={{ os_boot_disk }}
  clearpart --drives={{ os_boot_disk }} --all --initlabel
  autopart --type=plain -fstype=ext4 --ondisk={{ os_boot_disk }}
```

If `os_boot_disk` is null, then

```
os_partitioning: |
  clearpart --all --initlabel
  autopart --type=plain -fstype=ext4 
```

**Comment by oxedions** [comment]
Dear @sgaosdgr 

Ok noted. I agree with this. I will work on it soon, its not a major change :slightly_smiling_face:

**Comment by oxedions** [comment]
I added the feature  :slightly_smiling_face:

**Comment by sgaosdgr** [comment]
Thank you.
