### ISSUE TITLE
[FEATURE REQUEST] Add forward only zone to DNS server

### ISSUE THREAD

**Issue by sgaosdgr** [bluebanquise/bluebanquise#875]
In some case, a forward only zone is needed. For example, when a local storage cluster provides internal, private name resolution service.  The DNS server can be set to forward a query for storage_cluster1.local to the storage cluster's name service, and then the storage cluster's name service returns resolved ip address for storage_cluster1.local.

## Context

This change generates following zone configuration in named.conf:

```
one "storage_cluster1.local" IN {
        type forward;
        forward only;
        forwarders { 10.10.5.10; };
};
```

## Feature

1. Set two new variables:
```
ns_forward_only_domain: storage_cluster1.local
dns_forward_only_ip: 10.10.5.10
```

2. Add a zone section to named.conf.j2:
```
zone "{{ dns_forward_only_domain }}" IN {
        type forward;
        forward only;
        forwarders { {{ dns_forward_only_ip }}; };
};
```

## Additional data

OS: RockyLinux x86_64 9.3

**Comment by sgaosdgr** [comment]
Probably adding condition like:
```
{% if ns_forward_only_domain is defined and ns_forward_only_domain is string %}
     {% if dns_forward_only_ip is defined and ( dns_forward_only_ip | ansible.utils.ipaddr ) %}
        zone "{{ dns_forward_only_domain }}" IN {
             type forward;
             forward only;
             forwarders { {{ dns_forward_only_ip }}; };
        };
      {% endif %}
{% endif %}
```

**Comment by oxedions** [comment]
Dear @sgaosdgr 

Thank you for opening this feature request :blush: 
Apologies for the delay of my answer, I was sick during few days, and I couldn't connect. (managing kids as a zombie dad was already a full time job).

Reading your code, do you agree that this forward only should be a list instead of a single variable, as multiple zones could be forward only ?

**Comment by sgaosdgr** [comment]
Yes, it should be a list. 

Like:
```
dns_forward_only_domain:
    - name: storage_cluster1.local
      forwarder_ip: 10.10.5.10
   -  name: share2.local
      forwarder_ip: 10.1.10.15
```

Choose whatever naming scheme that's consistent with bluebanquise.

**Comment by oxedions** [comment]
Ok thanks a lot ! Once BB-23 is merged I will work on that.
