### ISSUE TITLE
[BUG] cgroup v2 is missing in bluebanuquise's repo slurm 

### ISSUE THREAD

**Issue by corentin-g** [bluebanquise/bluebanquise#876]
Dear team, 

Using the slurm provided in the bluebanquise repo, we were stopped by the following problem:
![image](https://github.com/bluebanquise/bluebanquise/assets/118284673/4cccd119-5405-4522-b629-33af7c0e72fb)

```bash
[root@management1 x86_64]# rpm -qlp slurm-23.11.1-1.el9.x86_64.rpm |grep -i "cgroup_.*so"
/usr/lib64/slurm/cgroup_v1.so
```

From another rpm:
```bash
[root@management1 x86_64]# rpm -qlp slurm-23.02.4..rpm |grep -i "cgroup_.*so"
/usr/lib64/slurm/cgroup_v1.so
/usr/lib64/slurm/cgroup_v2.so
```

Best regards

**Comment by oxedions** [comment]
cgroup v2 are now included. Please reopen this issue in case of needs :blush:
