### ISSUE TITLE
BB-24 - [BUG] collections/infrastructure/roles/dns_server/defaults/main.yml typo

### ISSUE THREAD

**Issue by sgaosdgr** [bluebanquise/bluebanquise#880]
collections/infrastructure/roles/dns_server/defaults/main.yml has a typo for dns_server_domain_name.

## Context

In "dns_server_domaine_name", "domaine" should be "domain". 

## Process

1. Search dns_server_domaine_name 

## Expected result

"dns_server_domain_name" is used everywhere

## Current result

Misspelled "dns_server_domaine_name"

## Possible Fix

Replacing "dns_server_domaine_name" with "dns_server_domain_name" everywhere.

**Comment by oxedions** [comment]
Dear @sgaosdgr 

Thanks a lot for opening this bug ! :blush: 
Yes, I made a bad translation here, apologies :innocent: 
I will fix that quickly.

**Comment by oxedions** [comment]
Fixed, it was also in hosts_file role
Thanks a lot @sgaosdgr :blush:
