### ISSUE TITLE
BB-25 - [FEATURE REQUEST] Set gid and uid in bluebanquise/bootstrap /online_bootstrap.sh 

### ISSUE THREAD

**Issue by sgaosdgr** [bluebanquise/bluebanquise#883]
Since we are now setting default gid and uid for bluebanquise to 377 in pxe_stack, we should also set the same uid/gid in bluebanquise/bootstrap /online_bootstrap.sh  

## Context

The online_bootstrap.sh script creates bluebanquise without specifying gid/uid.  A random uid/gid would be selected during account creation.  As a result, bluebanquise user and goup would have different uid/gid numbers from other cluster nodes. 

## Feature

Add one line for group creation and update user creation line:

Form:
```
id -u bluebanquise &>/dev/null || sudo useradd --create-home --home-dir /var/lib/bluebanquise --shell /bin/bash bluebanquise
```

To:
```
getent group bluebanquise &>/dev/null || sudo groupadd --gid 377 bluebanquise
getent passwd bluebanquise &>/dev/null || sudo useradd --gid 377 --uid 377 --create-home --home-dir /var/lib/bluebanquise --shell /bin/bash --system bluebanquise
```

## Additional data

For RockyLinux 9, need to add "--system" to avoid warning about uid 377 not in the right range.

**Comment by sgaosdgr** [comment]
Also for RockyLinux 9,  rpm package "clustershell" needs to be installed in addition to the python clustershell module.

**Comment by oxedions** [comment]
Dear @sgaosdgr 

Thank you for this feature request :blush: 
You are right, I will fix that.

Can you tell me why the clustershell package is also needed ? I am asling this because this package is not always available on all distributions.

**Comment by sgaosdgr** [comment]
Either online_bootstrap.sh or  configure_environment.sh would report error about not finding clustershell.  Installing clustershell package from epel makes the error go away.

**Comment by oxedions** [comment]
In theory this commit should have fixed it:
https://github.com/bluebanquise/bluebanquise/commit/c84ec8cbd653b085ef045b6399912cf0ac7f8a7c

So clustershell is installed via pip3 instead of package manager, and available when sourcing the python virtual environment.
And I made all tools that are deployed by roles independent of clustershell. If its still not the case, then its an issue :blush:

**Comment by sgaosdgr** [comment]
Let me double check on this

**Comment by oxedions** [comment]
That one should not have closed, re-opening until @sgaosdgr could check.

**Comment by sgaosdgr** [comment]
Confirmed clustershell rpm package (from epel repo) is not required.  The online_bootstrap.sh completes successfully with gid/uid 377 for bluebanquise group/user.
