### ISSUE TITLE
BB-27 - [BUG] Reverse lookup record for host alias name still being created when dns_server_enable_extended_names set to false

### ISSUE THREAD

**Issue by sgaosdgr** [bluebanquise/bluebanquise#888]
Reverse lookup record still being created when dns_server_enable_extended_names set to false.  No forward lookup record is created, which is expected. 

## Context

When ```dns_server_enable_extended_names: false",  there should be not forward nor reverse lookup record for host alias name created for a nodes.  But the result is that reverse lookup record still gets created.

## Process

1. Set variable, dns_server_enable_extended_names, to false
2. Run dns_server role
3. Query host name by an ip address
```
dig -x <ip address>
```

## Expected result

```
; ANSWER SECTION:
254.1.168.192.in-addr.arpa. 86400 IN   PTR     compute-0-1.cluster.local.
```
## Current result

```
;; ANSWER SECTION:
254.1.168.192.in-addr.arpa. 86400 IN   PTR     compute-0-1.cluster.local.
254.1.168.192.in-addr.arpa. 86400 IN   PTR     compute-0-1-net-1.cluster.local.
```

## Possible Fix

Update the dnf reverse lookup template file to not create an reverse lookup for host name alias. 

## Additional data

OS: RockyLinux 9.3 x86_64

**Comment by oxedions** [comment]
Dear @sgaosdgr 
Thank you for reporting this issue :blush: 
Indeed, I even forgot to fix bmcs, so both done now.
