### ISSUE TITLE
BB-28 - [BUG] The role dns_server is essentially broken in Debian [12]

### ISSUE THREAD

**Issue by erkrali** [bluebanquise/bluebanquise#893]
As the title says, the role can't possibly work in Debian. I have tried it with Debian 12 (bookworm), but I think most of the issues should also apply to earlier versions, because I don't think there has been any relevant change in the latest release.

Here are the issues I have found so far (there might be more):

* The main one: the main config file for Debian is `/etc/bind/named.conf`, not `/etc/named.conf`. This path is currently [hardcoded](https://github.com/bluebanquise/bluebanquise/blob/20757ec3f729b26bc018154f680fbdb3714402dc/collections/infrastructure/roles/dns_server/tasks/main.yml#L61), so it can't be fixed through variables.
* The generated file references `/etc/named.rfc1912.zones`. This is also [hardcoded](https://github.com/bluebanquise/bluebanquise/blob/20757ec3f729b26bc018154f680fbdb3714402dc/collections/infrastructure/roles/dns_server/templates/named.conf.j2#L117C10-L117C34) and doesn't exist on Debian either. In fact, the Debian-provided file refers to RFC 1918 and not 1912 (`/etc/bind/zones.rfc1918`)
* The `dns_server_root_key_file` variable needs to be updated for Debian. This can be updated by the user, though.
* ` dns_server_named_dir` should probably be `/etc/bind` in Debian. This can also be updated by the user.
* Also, generically, it doesn't follow the suggested Debian structure (`named.conf.options`, `named.conf.local`, etc.) This would be quite a minor issue, though, given that it will be managed by ansible.

**Comment by oxedions** [comment]
Dear @erkrali 

Thank you very much for reporting this issue! :blush: 

I added Ubuntu and Debian support very recently, and indeed I made a huge error here. I assumed bind9 configuration was close to EL8, which is not the case. I will fix this asap. Apologies for this.
I will do a pass on all services to check because this means some other tools might be impacted. DHCP and PXE are ok since I use them to deploy nodes during my tests, but I don't really get why my Ubuntu DNS worked as a forwarder. To investigate.

**Comment by erkrali** [comment]
No problem! Glad to be able to help!

I found some more issues, but I'm not sure how much they will help you if you are going to do your own tests anyway.

Also, I'm not a bind expert (I used so far `dnsmasq` for my local DNS needs), so I'm not sure what the proper solution would be either.

Anyway, since I have already found them, here they are:

* `option 'dnssec-enable' no longer exists` and `option 'dnssec-lookaside' no longer exists`. These might be specific to Debian 12, though, and might exist (and even be needed) in older versions.
* Everything referring to `/var/named` should likely now point to `/var/cache/bind`.
* Some folders under `/var/named`, eventually `/var/cache/bind`, don't exist, namely `dynamic` and `data`. I'm not sure if they should be somewhere else, or if they just need to be created (with the right ownership).
* The hint file `dns_server_root_hint_file` should probably be `/usr/share/dns/root.hints`.
* The ISC DLV keys aren't present, and in fact seem to be deprecated (using `dnssec-validation auto;` instead).

After changing these I managed to start the service, and it seems to work.

**Comment by oxedions** [comment]
Dear @erkrali 

It helps a lot ! This gives me a lot of guidelines on what to check first. Many many thanks ! :blush: 

Note that if you are looking for a DNS, I am strongly considering proposing a very simple Unbound as an alternative to Bind.
While I need to keep Bind for its ultra sophisticated possibilities that some users need, Unbound seems very adapted for a small/medium local cluster, and most users do not need Bind, but a small forwarder with a small local zone.

Unbound is mainly a cache/forwarder DNS. But it also supports local zones.

With the following configuration on Debian 12, I was able to test it:

File /etc/unbound/unbound.conf.d/bluebanquise.conf

```
server:
  interface: 0.0.0.0
  access-control: 10.10.0.0/16 allow
  local-zone: "cluster.local." transparent
  domain-insecure: "cluster.local"
  local-data: "foobar.cluster.local.  86400 IN A 10.10.0.77"
  local-data-ptr: "10.10.0.77  86400 foobar.cluster.local."
```

Then restart service, and test:

```
root@mgt9:/var/lib/bluebanquise# dig -x 10.10.0.77

; <<>> DiG 9.18.24-1-Debian <<>> -x 10.10.0.77
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35023
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;77.0.10.10.in-addr.arpa.	IN	PTR

;; ANSWER SECTION:
77.0.10.10.in-addr.arpa. 86400	IN	PTR	foobar.cluster.local.

;; Query time: 0 msec
;; SERVER: 10.10.0.9#53(10.10.0.9) (UDP)
;; WHEN: Mon Feb 19 21:05:58 CET 2024
;; MSG SIZE  rcvd: 86

root@mgt9:/var/lib/bluebanquise# dig foobar.cluster.local

; <<>> DiG 9.18.24-1-Debian <<>> foobar.cluster.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59983
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;foobar.cluster.local.		IN	A

;; ANSWER SECTION:
foobar.cluster.local.	86400	IN	A	10.10.0.77

;; Query time: 0 msec
;; SERVER: 10.10.0.9#53(10.10.0.9) (UDP)
;; WHEN: Mon Feb 19 21:06:03 CET 2024
;; MSG SIZE  rcvd: 65

root@mgt9:/var/lib/bluebanquise# 
```

Hope it helps you :wink:

**Comment by erkrali** [comment]
Hi!

Thanks for the tip. Bind is ok for me, especially if managed through bluebanquise almost transparently 😉 (thanks for the effort you put in it!)

Otherwise I would stay with `dnsmasq`. Nothing beats:

```
domain-needed
dns-loop-detect
server=a.b.c.d
server=e.f.g.h
expand-hosts
local=/mydomain.local/
domain=mydomain.local
```

and then just managing the local hosts file.

And, if needed, additional entries (also MX, or other kind of records) can be added directly just with:

```
host-record=node1,10.1.1.1
host-record=node2,10.1.1.2
mx-host=mail.mydomain.local,management1.mydomain.local,10
# ...
```

BTW, I also found a minor issue with the preseed file, but I think it's better to open a separate issue for that?

Again, thanks for the great work!

**Comment by oxedions** [comment]
Wow, indeed, dnsmasq beats it :smile: 
Not the first time I see dnsmasq, this is also an interesting alternative for small clusters.

I will fix bind asap. Should only be a matter of few days (my kids are sick one after another, its impossible to find free time).

Yes, please open another issue for the preseed bug. :blush: 
I am very interested with preseed feedbacks. I created the preseed using the documentation and examples and validated it with basic examples, but I strangely couldn't find advanced documentation, and so I discovered some parameters by luck while browsing the web.

**Comment by oxedions** [comment]
Dear @erkrali 

I fixed the dns_server role. Would you accept to have a quick look here: https://github.com/bluebanquise/bluebanquise/pull/898
Please ignore non dns_server related changes, this is just for me to add few things I found at the same time.
Also ignore the static code test failing, its related to the recent beegfs role provided by a user that I need to fix :blush:

**Comment by erkrali** [comment]
Sure, I'll try to have a deeper look and even test it later today (at least on debian 12).

I just skimmed briefly through it and it looks much nicer now, so I don't expect any big issue. Also, as I said, from the general structure it looks much nicer!

Thanks a lot for the great work!

**Comment by erkrali** [comment]
So, I just tested it and I can confirm that it works in my debian 12 setup 😊

**Comment by erkrali** [comment]
I can now confirm that it works and that the problem was on my side: I had forgotten to enable recursion.

**Comment by oxedions** [comment]
Thanks a lot @erkrali for checking and testing ! I made some checks on other distros too and now it seems to work.
I merged it in master :blush: 

Closing the issue.
