### ISSUE TITLE
[BUG] nfs_server: auto directories creation should be optional in BB 1.6

### ISSUE THREAD

**Issue by ginomcevoy** [bluebanquise/bluebanquise#895]
## Context

New BlueBanquise adds "auto directories creation" feature to nfs_server role. This has been ported to BB 1.6, but setting "nfs_server_create_directories_if_not_exist: True" is a breaking change. This change caused issues in our automated test environments, as the permissions of the mount dir is changing.

For BB 1.6, the variable should be set to False by default, to keep feature optional.

## Process

Run nfs_server role

## Expected result

New functionality of creating the NFS directories should be optional on BB 1.6.
Also, BB should not modify existing NFS directories, for example if they had mode 0777.

## Current result

Permissions of existing NFS share directories are being forced to 0755

## Possible Fix

Apply this fix to BB 1.6:
```
--- a/roles/core/nfs_server/defaults/main.yml     2024-02-26 14:36:39.427496928 +0000
+++ b/roles/core/nfs_server/defaults/main.yml     2024-02-26 14:36:47.481511244 +0000
@@ -1,2 +1,2 @@
 ---
-nfs_server_create_directories_if_not_exist: true
+nfs_server_create_directories_if_not_exist: false
```
## Additional data

There should be a check with stat task on each directory before the file task, and only apply the file task if the stat result shows the directory does not exist (and if the flag is set to True).

I could open that as a separate bug for BB 3.0.

**Comment by oxedions** [comment]
Dear @ginomcevoy 
Many thanks for this issue report :blush: 

Do you think you could do a small PR to fix this ? I am a little under the wave 😅

**Comment by ginomcevoy** [comment]
Hello, I will open a PR with this very soon.

**Comment by oxedions** [comment]
Closing issue, thanks for the fix !!
