### ISSUE TITLE
[BUG] infrastructure/ssh_client ignore ssh_client_userknownhostsfile

### ISSUE THREAD

**Issue by lmagdanello** [bluebanquise/bluebanquise#901]
Infrastructure/ssh_client role ignoring UserKnownHostsFile.

## Context

If you add as hostvars `ssh_client_userknownhostsfile: /dev/null`, e.g., it will not be applied due to a miss configuration in the Jinja2 template.

## Expected result

```
ssh_client_userknownhostsfile: /dev/null

Host c001
    StrictHostKeyChecking False
    UserKnownHostsFile /dev/null
    Hostname %h-ice1-1
```

**Comment by oxedions** [comment]
Dear @lmagdanello 

Thank you for opening this issue ! :blush: 

Well, after investigating, issue is much worse than that. I don't know what I did, but the code is really bad :rofl: 

```
{# Macro to avoid redundancy #}
{% macro write_host(host, host_vars, ssh_jump) %}
Host {{ host }}
    {% if host_vars['ssh_client_stricthostkeychecking'] is defined and host_vars['ssh_client_stricthostkeychecking'] is not none %}
    StrictHostKeyChecking {{ host_vars['ssh_client_stricthostkeychecking'] }}
    {% endif %}
    {% if host_vars['ssh_client_userknownhostsfile'] is defined and host_vars['ssh_client_userknownhostsfile'] is not none %}
    UserKnownHostsFile {{ ssh_client_userknownhostsfile }}
    {% endif %}
    {% if host_vars['ssh_client_loglevel'] is defined and host_vars['ssh_client_loglevel'] is not none %}
    LogLevel {{ host_vars['ssh_client_loglevel'] }}
    {% endif %}
    {% if ssh_jump is none %}
      {% set host_to_be_used_network = host_vars['j2_icebergs_main_network_dict'][j2_current_iceberg] | default(none, true) %}
    Hostname %h{% if host_to_be_used_network is not none %}-{{ host_to_be_used_network }}{% endif %}

    {% else %}
    Hostname %h
    ProxyJump {{ ssh_jump }}
    {% endif %}
{% endmacro %}
```

You can see I used `host_vars['ssh_client_stricthostkeychecking']` for example, which does not exist at all !!

It should be `hostvars[host]['ssh_client_stricthostkeychecking']` instead, and for efficiency reasons, I should use a buffer in the main loop.

I am really sorry for this code, I must have been bugged when I did that :slightly_smiling_face:

**Comment by oxedions** [comment]
I will fix that as soon as possible !

**Comment by lmagdanello** [comment]
Hey @oxedions,

I made the necessary changes: added the individual variables that were missing from defaults and encapsulated the variables in the buffer for optimization.

I did some tests on my bluebanquise-box:

```
# Global parameters

    Host mgt1

    Host node00
    UserKnownHostsFile /tmp

    Host node01
```

**Comment by lmagdanello** [comment]
I was unsure whether to keep it in 1.2.2 or 1.2.3, I can correct it if it's better to keep it in just one version given that it's a similar fix to the role.

**Comment by lmagdanello** [comment]
Bug fixed with [!902](https://github.com/bluebanquise/bluebanquise/pull/902)
