### ISSUE TITLE
BB-30 - [FEATURE REQUEST] Add support of infiniband in bluebanquise.infrastructure.nic role

### ISSUE THREAD

**Issue by jpm38** [bluebanquise/bluebanquise#904]
[Provide here general introduction to the feature request, and why it is relevant to this repository]

The community.general.nmcli module supports now infiniband bonding, by configuring a new option named slave_type.
We need this option to be supported in the bluebanquise nic role to be able to configure infiniband bonds.

[Provide more detailed introduction to the feature request context. Is your feature request related to a problem? Please describe.]

Support of infiniband bonding configuration.

[Describe the solution you'd like. Please be precise.]

Support on nmcli module slave_type option in nic role.

**Comment by oxedions** [comment]
Dear @jpm38 

Many thanks for this request. This is a small dev, I will do it right now.
Linking this to https://github.com/bluebanquise/bluebanquise/issues/905 since you requested both :slightly_smiling_face:
