### ISSUE TITLE
iceberg_master and iceberg_level must be renamed everywhere with the "bb_" prefix.

### ISSUE THREAD

**Issue by jpm38** [bluebanquise/bluebanquise#905]
[Provide general introduction to the issue logging and why it is relevant to this repository.]

I've found some occurrences of iceberg_master and icerberg_level in the new BB 3.0

[Provide more detailed introduction to the issue context.]

the new stack is based on bb_iceberg_* variables

**Comment by oxedions** [comment]
Linked to https://github.com/bluebanquise/bluebanquise/issues/904, aka BB-30
