### ISSUE TITLE
[FEATURE REQUEST] Prometheus add remote_write feature

### ISSUE THREAD

**Issue by sgaosdgr** [bluebanquise/bluebanquise#908]
Please add remote_write feature for prometheus to allow exporting metrics to other 3rd party log/metric collector 

## Context

Currently Prometheus configuration does not include remote_write configuration.  It would be to good to allow this setting for users to send log/metric to other 3rd party collector. 

## Feature

1. Add a variable,  prometheus_server_remote_write:
```
prometheus_server_remote_write: |
- url: <url for metric collector>
  name: <metric_name>
  remote_timeout: 120s
  bearer_token: ********************
```

2. Add following to collections/monitoring/roles/prometheus/templates/prometheus.yml.j2:
```
{% if prometheus_server_remote_write is defined and prometheus_server_remote_write is not none %}
{{ prometheus_server_remote_write }}
{% endif %}
```

**Comment by sgaosdgr** [comment]
Actually, this variable, prometheus_server_prometheus_raw_configuration, does the trick.

**Comment by oxedions** [comment]
Ok thanks :blush:
