### ISSUE TITLE
BB-32  - [FEATURE REQUEST] add prometheus expoert raw configuration 

### ISSUE THREAD

**Issue by sgaosdgr** [bluebanquise/bluebanquise#909]
Currently the template for exporter service does not allow adding additional configuration lines. 

## Context

Please add a new variable, say, exporter_service_raw_configuration, for [Service] section.  This variable can have multiple lines like:
```
SyslogIdentifier=node_exporter
Restart=always
RestartSec=1
StartLimitInterval=0

ProtectHome=read-only
NoNewPrivileges=yes

ProtectSystem=full
```

The template, collections/monitoring/roles/prometheus/templates/exporter.service.j2, can be updated like:
```
[Unit]
  Description={{ item.service }}
  Wants=network-online.target
  After=network-online.target

[Service]
  User={{ item.user | default('root') }}
  Group={{ item.group | default('root') }}
  Type=simple
  WorkingDirectory=/etc/{{ item.service }}/
  ExecStart={{ item.path | default('/bin/'+item.service) }} \
  {{ item.launch_parameters | default('') | indent(2, True) }}

{% if  exporter_service_raw_configuration is defined and exporter_service_raw_configuration is not none %}
{{ exporter_service_raw_configuration }}
{% endif %}

[Install]
  WantedBy=multi-user.target
```

**Comment by oxedions** [comment]
Dear @sgaosdgr 

Thank you for this request :blush: 

Ok, I will work on that asap, since its a small task I will do it in the middle of a larger one.

**Comment by oxedions** [comment]
Dear @sgaosdgr 

Would that be ok for you ?

https://github.com/bluebanquise/bluebanquise/pull/917

**Comment by sgaosdgr** [comment]
Yes. The code changes looks good to me.

Simon
