### ISSUE TITLE
BB-33 - [FEATURE REQUEST] Option to install additional packages during kickstart install

### ISSUE THREAD

**Issue by sgaosdgr** [bluebanquise/bluebanquise#918]
It's useful to add an option to install user specified additional packages during kickstart installation.  

## Context

Currently only curl (and sudo) packages are installed during kickstart installation. It's useful to allow users to define additional packages to install. 

## Feature

Update collections/infrastructure/roles/pxe_stack/templates/RedHat/kickstart.cfg.j2 with following lines:
```
.....
##### Packages
%packages
@core
curl
{% if pxe_stack_os_base_additional_packages is defined and pxe_stack_os_base_additional_packages is not none %}
{% for pkg in pxe_stack_os_base_additional_packages %}
{{ pkg }}
{% endfor %}
{% endif %}
{% if not pxe_stack_enable_root %}
sudo
{% endif %}
%end
.....
```

In defaults/main.yml, define the variable:
```
pxe_stack_os_base_additional_packages: []
```

For example, if user wants to install rsync, pciutils.
```
pxe_stack_os_base_additional_packages:
   - pciutils
   - rsync

```

## Additional data

In the example, curl, pcituils, rsync are installed during OS installation.

**Comment by oxedions** [comment]
Dear @sgaosdgr 

This request make sense, I will do that asap :blush: 
Maybe I should also check how I can allow users to add additional repos. I know its feasible with raw content, but a dedicated variable would be more user friendly.

**Comment by oxedions** [comment]
The code should be ok now, I also added the instructions in the readme. Please let me know if anything goes wrong.
