### ISSUE TITLE
BB-33 - [BUG] Role sudoers not handle multiple users properly

### ISSUE THREAD

**Issue by sgaosdgr** [bluebanquise/bluebanquise#919]
Role sudoers does not handle multiple users properly.

## Context

When there are multiple users in a sudoer file, role sudoers does not handle user list update well. It ends up with multiple lines of sudo privileges including the users already removed from the user list.

## Process

For example, the initial sudoers variable contains:
```
  - name: user1, user2, user3, user4, user5, user6
    file_name: /etc/sudoers.d/group1
    privilege: "ALL=NOPASSWD: /usr/bin/ls, /usr/bin/netstat, /usr/bin/lspci, /usr/bin/date"
```

The initial output /etc/sudoers.d/group1 would have all the users in one line like:
```
user1, user2, user3, user4, user5, user6 ALL=NOPASSWD: /usr/bin/ls, /usr/bin/netstat, /usr/bin/lspci, /usr/bin/date
```

When removing any user from beginning to next to last one, the privilege gets duplicated and the removed users are not deleted from the sudoer file. 

For example, deleting "user1", the output would be:
```
--- before: /etc/sudoers.d/group1 (content)
+++ after: /etc/sudoers.d/group1 (content)
@@ -1 +1,2 @@
 user1, user2, user3, user4, user5, user6 ALL=NOPASSWD: /usr/bin/ls, /usr/bin/netstat, /usr/bin/lspci, /usr/bin/date
+user2, user3, user4, user5, user6 ALL=NOPASSWD: /usr/bin/ls, /usr/bin/netstat, /usr/bin/lspci, /usr/bin/date

changed: [mgt1] => (item={'name': 'user2, user3, user4, user5, user6', 'file_name': '/etc/sudoers.d/group1', 'privilege': 'ALL=NOPASSWD: /usr/bin/ls, /usr/bin/netstat, /usr/bin/lspci, /usr/bin/date'})
```

```
$ sudo cat /etc/sudoers.d/group1
user1, user2, user3, user4, user5, user6 ALL=NOPASSWD: /usr/bin/ls, /usr/bin/netstat, /usr/bin/lspci, /usr/bin/date
user2, user3, user4, user5, user6 ALL=NOPASSWD: /usr/bin/ls, /usr/bin/netstat, /usr/bin/lspci, /usr/bin/date
```

After that, deleting user4, output would be like:
```
--- before: /etc/sudoers.d/group1 (content)
+++ after: /etc/sudoers.d/group1 (content)
@@ -1,2 +1,3 @@
 user1, user2, user3, user4, user5, user6 ALL=NOPASSWD: /usr/bin/ls, /usr/bin/netstat, /usr/bin/lspci, /usr/bin/date
 user2, user3, user4, user5, user6 ALL=NOPASSWD: /usr/bin/ls, /usr/bin/netstat, /usr/bin/lspci, /usr/bin/date
+user2, user3, user5, user6 ALL=NOPASSWD: /usr/bin/ls, /usr/bin/netstat, /usr/bin/lspci, /usr/bin/date

changed: [mgt1] => (item={'name': 'user2, user3, user5, user6', 'file_name': '/etc/sudoers.d/group1', 'privilege': 'ALL=NOPASSWD: /usr/bin/ls, /usr/bin/netstat, /usr/bin/lspci, /usr/bin/date'})
```

```
$ sudo cat /etc/sudoers.d/group1
user1, user2, user3, user4, user5, user6 ALL=NOPASSWD: /usr/bin/ls, /usr/bin/netstat, /usr/bin/lspci, /usr/bin/date
user2, user3, user4, user5, user6 ALL=NOPASSWD: /usr/bin/ls, /usr/bin/netstat, /usr/bin/lspci, /usr/bin/date
user2, user3, user5, user6 ALL=NOPASSWD: /usr/bin/ls, /usr/bin/netstat, /usr/bin/lspci, /usr/bin/date
```

## Expected result

The deleted users should be removed from the sudoer file. 

## Current result

The deleted users are still in the sudoer file and there are duplicated lines. 

## Possible Fix

One option to fix this issue is using blockinfile.  Any change to sudoer permission setting would override/replace existing block so no any previous sudo setting left behind.

For this option, update collections/infrastructure/roles/sudoers/tasks/main.yml:
```
- name: blockinfile <|> Add sudoers users and groups
  ansible.builtin.blockinfile:
    path: "{{ item.file_name | default('/etc/sudoers') }}"
    state: present
    create: true
    owner: root
    group: root
    mode: '0600'
    block: |
      {{ item.name }} {{ item.privilege }}
    validate: 'visudo -cf %s'
  loop: "{{ sudoers }}"
  when: sudoers is defined and sudoers
```

## Additional data

With blockinfile, the downside is there will be only one block can be set in /etc/sudoers file. Therefore not possible to set separate sudo permissions for separate user and group.  But this issue can be solved with dedicated sudoer files for each user list or group.  Using dedicated sudoer file is more flexible anyway.
```
  - name: stone, wood
    privilege: ALL=(ALL) NOPASSWD:ALL       
```

**Comment by sgaosdgr** [comment]
Actually if only set one user or group for each sudoer file, then the current code works as expected 

The bigger issue is that when a user or group  is removed from sudoer list, the sudoer file for that user or group is left behind instead of being deleted. So current sudoers role only does sudoer file addition, is not able to purge unwanted sudoer file.

**Comment by oxedions** [comment]
Dear @sgaosdgr 

Thank you very much for this bug report, and for provided a fix. :blush: 
I agree with you, and so I updated BB-33 with your fix. It could be possible to bypass the limitation from blockinline by pre-calculating each file content in a fact, but this seems overkill for me.

Code is here, waiting for it to pass validation : https://github.com/bluebanquise/bluebanquise/pull/922

**Comment by oxedions** [comment]
And merged :blush:

**Comment by sgaosdgr** [comment]
Thank you!

Simon
