### ISSUE TITLE
BB-35 - blockinfile does not work with loop 

### ISSUE THREAD

**Issue by vedmonds** [bluebanquise/bluebanquise#931]
https://github.com/bluebanquise/bluebanquise/blob/06d0c1b0daa46928e717988c55e34fdcb0d7a432/collections/infrastructure/roles/sudoers/tasks/main.yml#L9

Due to how `ansible.builtin.blockinfile` is reg-exing if you use with the list `sudoers`, it will replace the entire block with each element of list.  The net effect being you only see the result of the last element. 

This can cause breaking changes if user running the playbook has been granted their sudo rights to carry out playbook steps via this role. 

There have been several edits to this role, I am wondering why not use ansible.community.sudoers task.

**Comment by vedmonds** [comment]
If you are married to use of blockinfile, you would need to add a `marker` that was dependent on `”{{ item }}` so that it will be additive for distinct block items, rather than it targeting one block for all items.

But again I wonder if there is an implementation that could leverage `ansible.community.sudoers` instead

**Comment by oxedions** [comment]
Dear @vedmonds 

My apologies for the delay of my answer.
This is kids holidays in my country, so no school = dad's duties.

I think when I created this role, I just missed the sudoers community module, or maybe it wasnt just already there at this moment.
I will try to switch the role to this module next week :blush:

**Comment by oxedions** [comment]
Dear @vedmonds 

Here is the switch to sudoers module. Can you confirm this match your needs ? : https://github.com/bluebanquise/bluebanquise/pull/937/commits/708fa89fb753c279292bea8a56b2ba6e8456ed87

@sgaosdgr can you confirm this change does not break your setup ? I know you were also using this role, and I didn't kept any retro compatibility. If this is needed, I can embed some advanced logic to allow retro-compatibility.

**Comment by vedmonds** [comment]
looks good to me
