### ISSUE TITLE
BB-35 - [FEATURE REQUEST] slurm_slurmdbd_conf_additional_content variable/section for slurmdbd.conf template

### ISSUE THREAD

**Issue by vedmonds** [bluebanquise/bluebanquise#933]
Add a variable (`slurm_slurmdbd_conf_additional_content`) to add additional content to slurmdbd.conf template, similar to what is available in slurm.conf template via `slurm_slurm_conf_additional_content`

https://github.com/bluebanquise/bluebanquise/blob/master/collections/hpc/roles/slurm/templates/slurmdbd.conf.j2

## Context

To be able to leverage additional specs within the fixed slurmdbd.conf template

## Feature
Within `collections/hpc/roles/slurm/templates/slurmdbd.conf.j2`
```
## Additional content if exist
{% if slurm_slurmdbd_conf_additional_content is defined and slurm_slurmdbd_conf_additional_content is iterable %}
  {% for slurmdbd_slurm_conf_content in slurm_slurmdbd_conf_additional_content %}
{{ slurm_slurmdbd_conf_content | default('', true) }}                                                                                                                       
  {% endfor %}
{% endif %}
```

**Comment by oxedions** [comment]
Dear @vedmonds 

Thank you for this feature request. Yes it makes sens, I will add this :blush:

**Comment by oxedions** [comment]
Dear @vedmonds 

Here is the feature requested : https://github.com/bluebanquise/bluebanquise/pull/937/commits/d96173219b8dd3041593acc0533d4c2e73508e86

Does it match your request ?

**Comment by vedmonds** [comment]
Yes thank you!

**Comment by oxedions** [comment]
Thanks a lot for the feedback. PR is merged :blush: 
Please reopen this issue if you encounter any issues.
