### ISSUE TITLE
BB-35 - [BUG] Rsyslog client.conf missing forward rules when setting specific log4 variable

### ISSUE THREAD

**Issue by sgaosdgr** [bluebanquise/bluebanquise#936]
When setting specific log4 variable in group_vars/all/network.yml for a network, client.conf is not generated correctly and therefore missing the forwarding role.

## Context

In https://github.com/bluebanquise/bluebanquise/blob/master/collections/logging/roles/rsyslog/templates/client.conf.j2,
the variable names are not consistent at line 32 and 33:

```
    {% for rsyslog_server in (networks[j2_node_main_network]['services']['log4'] | default(networks[j2_node_main_network]['services']['log'], true)) %}
        {% if (log_server.ip4 is defined and (log_server.ip4 | ansible.utils.ipaddr)) or (log_server.hostname is defined and rsyslog_server.hostname is not none) %}
```

The correct variable name should rsyslog_server.ip4 instead of log_server.jp4.

Here are the code changes when all the issues are resolved and client.conf is correctly created:
```
$ diff client.conf.j2 client.conf.j2.orig
1d0
< #jinja2: lstrip_blocks: "True"
34c33
<         {% if (rsyslog_server.ip4 is defined and (rsyslog_server.ip4 | ansible.utils.ipaddr)) or (rsyslog_server.hostname is defined and rsyslog_server.hostname is not none) %}
---
>         {% if (log_server.ip4 is defined and (log_server.ip4 | ansible.utils.ipaddr)) or (log_server.hostname is defined and rsyslog_server.hostname is not none) %}
39c38
< $ActionQueueFileName fwdRule  # unique name prefix for spool files
---
> $ActionQueueFileName fwdRule{{ loop.count }} # unique name prefix for spool files
44c43
<         {% if rsyslog_server.ip4 is defined and (rsyslog_server.ip4 | ansible.utils.ipaddr) %}
---
>         {% if rsyslog_server.ip4 is defined and (log_server.ip4 | ansible.utils.ipaddr) %}
```
## Process

1. Set network specific log4 variable like:
```
   services:
      dns4: 
        - ip4: 10.10.1.5
          name: ns01
      log4: 
        - ip4: 10.10.1.6
          name: log_server01
```
2. Then run:
```
ansible-playbook playbooks/compute.yml -i inventory/ --tags rsyslog
```
## Expected result

The generated client.conf file should include the forwarding rule section like:
```
#### FORWARD RULES ####

# ### begin forwarding rule ###
# Remote Logging (we use TCP for reliable delivery)
# An on-disk queue is created for this action. If the remote host is
# down, messages are spooled to disk and sent when it is up again.
$ActionQueueFileName fwdRule  # unique name prefix for spool files
$ActionQueueMaxDiskSpace 1g   # 1gb space limit (use as much as possible)
$ActionQueueSaveOnShutdown on # save messages to disk on shutdown
$ActionQueueType LinkedList   # run asynchronously
$ActionResumeRetryCount -1    # infinite retries if host is down
*.* @@10.10.1.6:514
# ### end of the forwarding rule ###
```

## Current result

The generated client.conf file does not have forwarding rule section.

## Possible Fix

Replacing log_server with rsyslog_server. See above file diff output.

## Additional data

The issue is  found on RockyLinux 9.3 x86_64.

**Comment by oxedions** [comment]
Dear @sgaosdgr

Thank you for reporting this issue ! I will fix this asap, I have a small slot today at last ! :blush:

**Comment by oxedions** [comment]
Dear @sgaosdgr 

Here is the fix ! I hope its ok this way.
Note that default now is "log" and not "log4" for services, since ip4 specify if its ipv4 or ipv6 ip :blush: 
I kept log4 as retro compatibility.

https://github.com/bluebanquise/bluebanquise/pull/937/commits/403bd0f42a868b25002b7049c9683542b4637e5f

**Comment by sgaosdgr** [comment]
Thank you for quick response.

At line 38 of client.conf.j2, "fwdRule{{ loop.count }}" does not work.

```
38  $ActionQueueFileName fwdRule{{ loop.count }} # unique name prefix for spool files
```
I had to remove {{ loop.count }} to get it working. Can you double check?

**Comment by oxedions** [comment]
Dear @sgaosdgr 

Oups, apologies I missed that part of your diff.
Hum, there is indeed a bug, it should be loop.index and not loop.counter.
Removing the variable like you did will lead to issues later, for users who have multiple servers to reach :slightly_smiling_face: 

I will fix this.

**Comment by oxedions** [comment]
PR is merged. However I let this issue open until you confirm me that the patch provided solves your issues. :blush:

**Comment by sgaosdgr** [comment]
Thank you for the making the fix.

Can you add the following line to beginning of client.conf.j2?

```
#jinja2: lstrip_blocks: "True"
```

Without this line:
```
#### FORWARD RULES ####

            # ### begin forwarding rule ###
# Remote Logging (we use TCP for reliable delivery)
# An on-disk queue is created for this action. If the remote host is
# down, messages are spooled to disk and sent when it is up again.
$ActionQueueFileName fwdRule1 # unique name prefix for spool files
$ActionQueueMaxDiskSpace 1g   # 1gb space limit (use as much as possible)
$ActionQueueSaveOnShutdown on # save messages to disk on shutdown
$ActionQueueType LinkedList   # run asynchronously
$ActionResumeRetryCount -1    # infinite retries if host is down
        *.* @@10.10.10.8:514
        # ### end of the forwarding rule ###
```

**Comment by oxedions** [comment]
Indeed, apologies. Fixed :blush:

**Comment by sgaosdgr** [comment]
Thanks. Confirmed the fix works nicely
