### ISSUE TITLE
BB-36 - [BUG] Slurmdbd.conf.j2 template not working with a remote dedicated mariadb sever

### ISSUE THREAD

**Issue by sgaosdgr** [bluebanquise/bluebanquise#942]
Template https://github.com/bluebanquise/bluebanquise/blob/master/collections/hpc/roles/slurm/templates/slurmdbd.conf.j2  does not work well when slurm database is on another host from where slurmdbd is running. 

## Context

For slurm, `DbdHost` refers to the machine where slurmbdb is running, `StorageHost` the machine where mariadb server is running.  `DbdHost` and `StorageHost` can be the same machine when running local mariadb/mysql database server. But when mariadb/mysql is running on another machine, `DbdHost` and `StorageHost` would be different. 

To be consistent, it's good to always use `DbdHost` and `StorageHost` variables.

Here is the updated version that works for both cases:
```
#jinja2: lstrip_blocks: True
#### Blue Banquise file ####
## {{ansible_managed}}

# Documentation:
# https://slurm.schedmd.com/slurmdbd.conf.html

## Authentication
AuthInfo=/var/run/munge/munge.socket.2
AuthType=auth/munge
SlurmUser=slurm

{% if slurm_enable_local_mysql is defined and slurm_enable_local_mysql %}
## Mariadb server
DbdHost={{ slurm_accounting_mysql_login_host | default('localhost', true) }}
{% else %}
# SlurmDdb info
DbdAddr={{ slurm_contoller_ip_address | default(ansible_default_ipv4.address) }}
DbdHost={{ slurm_controller_hostname | default(ansible_hostname) }}
DbdPort={{ slurm_dbd_port | default('6819') }}
MessageTimeout=10
DefaultQOS=normal
PluginDir=/usr/lib64/slurm
TrackWCKey=yes
{% endif %}

## Log and pid
LogFile={{ slurm_slurmdbdlogfile }}
DebugLevel={{ slurm_slurmdbddebug }}
PidFile=/var/run/slurmdbd.pid

## Storage
StorageType=accounting_storage/mysql
{% if slurm_enable_local_mysql is defined and slurm_enable_local_mysql %}
StorageUser={{ slurm_accounting_storage_user }}
StoragePass={{ slurm_accounting_storage_pass }}
{% else %}
StorageHost={{ slurm_accounting_mysql_login_host }}
StoragePort={{ slurm_accounting_mysql_login_port }}
StorageUser={{ slurm_accounting_mysql_login_user }}
StoragePass={{ slurm_accounting_mysql_login_password }}
{% endif %}

## Additional content if exist
{% if slurm_slurmdbd_conf_additional_content is defined and slurm_slurmdbd_conf_additional_content is iterable %}
  {% for slurm_slurmdbd_conf_content in slurm_slurmdbd_conf_additional_content %}
{{ slurm_slurmdbd_conf_content | default('', true) }}                                                                                                                       
  {% endfor %}
{% endif %}
```

`## Mariadb server` for Dbdhost section is incorrect,  It should be renamed to SlurmDbd.  Using condition here is just for back compatibility.  The best fix is to use one set of variables for both local and remote Mariadb server.   

## Process

1. Install and set up Mariadb server on another machine. Create default slurm database and user account
2. Set `slurm_enable_local_mysql`, ` slurm_accounting_mysql_create_database`, `slurm_accounting_mysql_create_user` to false
3. Set `slurm_accounting_mysql_login_host`, `slurm_accounting_mysql_login_port`, `slurm_accounting_mysql_login_user`, `slurm_accounting_mysql_login_password` based on step 1.
4. Apply role `slurm`

## Expected result

Slurmdbd is able to connect to Mariadb server on a different machine

## Current result

It failed making the connection.

## Possible Fix

See the updated file above.

## Additional data

This is tested with RockyLinux  9 x86_64

**Comment by oxedions** [comment]
Dear @sgaosdgr 

Thank you for this request. :blush: 

Indeed, I didn't thought about clusters where mariadb is external or on another node, which is in fact a good practice.

Ok for me, I will add this fix asap. I will take this opportunity to upgrade major slurm version to 23.11.7.

**Comment by oxedions** [comment]
Dear @sgaosdgr 
I added a fix in https://github.com/bluebanquise/bluebanquise/pull/944, can you check its ok for you ? I tried to be retro-compatible in the code.

**Comment by oxedions** [comment]
I will close this issue, please let me know if this issues is still there :wink:
