### ISSUE TITLE
[BUG] pxe_stack role: os_autoinstall_packages variable is not taken into account

### ISSUE THREAD

**Issue by jpm38** [bluebanquise/bluebanquise#947]
When setting the variable:
os_autoinstall_packages:
  - pkg1
  - pkg2
 
into equipment_profile.yml, the kickstart result file does not contain the packages into %packages section.

**Comment by oxedions** [comment]
Dear @jpm38 

Thank you for this issue ! :blush: 

I will fix this asap !

**Comment by oxedions** [comment]
Fixed in https://github.com/bluebanquise/bluebanquise/pull/949 :slightly_smiling_face: 
Let me know if it doesnt work as expected.
