### ISSUE TITLE
BB-38 - [BUG] systemd service file, prometheus.service, should be set to 0644 instead of 0755

### ISSUE THREAD

**Issue by sgaosdgr** [bluebanquise/bluebanquise#950]
In https://github.com/bluebanquise/bluebanquise/blob/master/collections/monitoring/roles/prometheus/tasks/server_prometheus.yml, the permission for /etc/systemd/system/prometheus.service is currently set to 0755.  For a systemd service file, the permission should be 0644

## Context

The permission for /etc/systemd/system/prometheus.service is currently set to 0755.  It triggers warnings by systemd. The right permission should be 0644.  

## Process

Apply role prometheus.  Check permission on /etc/systemd/system/prometheus.service. 

## Expected result

The expected permission should be 0644. 

## Current result

0755

## Possible Fix

Change line 30 to:
`    mode: 0644`

## Additional data

Tested on RockyLinux 9 x86_64.

**Comment by sgaosdgr** [comment]
Same issue in https://github.com/bluebanquise/bluebanquise/blob/master/collections/monitoring/roles/prometheus/tasks/client.yml line 42

**Comment by oxedions** [comment]
Closing since PR was merged.
