### ISSUE TITLE
[BUG] bluebanquise-diskless tool - Issue with the clone option (option 6)

### ISSUE THREAD

**Issue by seth4243** [bluebanquise/bluebanquise#953]
Hello, 

We have an issue when we are using the "6 - Clone a reference image" option in bluebanquise-diskless. 
The file boot.ipxe in /var/www/html/pxe/diskless/{forlder_image_name}/boot.ipxe didn't use the good new path of the new clone. 

For instance : 
Reference image: rhel_9.4_ref 
Cloned reference image : rhel_9.4_ref_clone

/var/www/html/pxe/diskless/**rhel_9.4_ref_clone**/boot.ipxe file content : 

`#!ipxe
        echo |
        echo | Entering diskless/images/rhel_9.4_ref/boot.ipxe
        echo |
        set image-kernel vmlinuz-5.14.0-427.test.el9.x86_64
        set image-initramfs initramfs-5.14.0-427.test.el9.x86_64.img
        echo | Now starting nfs image boot.
        echo |
        echo | Parameters used:
        echo | > Image target: rhel_9.4_ref
        echo | > Console: ${eq-console}
        echo | > Additional kernel parameters: ${eq-kernel-parameters} ${dedicated-kernel-parameters}
        echo |
        echo | Loading linux ...
        kernel http://${next-server}/pxe/diskless/rhel_9.4_ref/${image-kernel} initrd=${image-initramfs} selinux=0 text=1 root=nfs:${next-server}:/nfs/diskless/rhel_9.4_ref,vers=4.2,rw rw ${eq-console} ${eq-kernel-parameters} ${dedicated-kernel-parameters} rd.net.timeout.carrier=30 rd.net.timeout.ifup=60 rd.net.dhcp.retry=4
        echo | Loading initial ramdisk ...
        initrd http://${next-server}/pxe/diskless/rhel_9.4_ref/${image-initramfs}
        echo | ALL DONE! We are ready.
        echo | Booting in 4s ...
        echo |
        echo +----------------------------------------------------+
        sleep 4
        boot
`

**Comment by oxedions** [comment]
Dear @seth4243 

Indeed, thank you very much for raising this issue ! :blush: 

I will fix this asap :wink:

**Comment by ginomcevoy** [comment]
Hello @oxedions , I am making some changes to bluebanquise-diskless in the ginomcevoy/bluebanquise-diskless branch.
I can include the fix for this issue in the PR to merge the changes if that is OK for you, I plan to open the PR tomorrow.

**Comment by oxedions** [comment]
Hello @ginomcevoy 

Yes, that would be nice, thanks a lot ! Its just a small fix, I forgot to edit the boot.ipxe file when cloning :blush:
