### ISSUE TITLE
[FEATURE REQUEST] infrastructure/nic role : make the connection restart timeout configurable

### ISSUE THREAD

**Issue by jpm38** [bluebanquise/bluebanquise#956]
The nic role is providing a way to force the connection restart after nic configuration using the "nic_force_nic_restart" variable.
The problem is that the time to wait between nmcli con down and nmcli con up is hard-coded to 2 seconds, and depending on the nodes, this time is not sufficient and the connection restart fails/

## Feature

The feature is to add a new default variable "nic_restart_timeout" and modify the main.yml for both Suse and Redhat as follows:

 - name: shell <|> Force apply nic settings
-  ansible.builtin.shell: "nmcli con down {{ item.item.interface }} && sleep 2 && nmcli con up {{ item.item.interface }}"
+  ansible.builtin.shell: "nmcli con down {{ item.item.interface }} && sleep {{ nic_restart_timeout }} && nmcli con up {{ item.item.interface }}"

**Comment by oxedions** [comment]
Dear @jpm38 

Thank you for this issue.
I merged your PR :slightly_smiling_face:
