### ISSUE TITLE
[FEATURE REQUEST] infrastructure/dns_client : be able to set dns servers using a new variable

### ISSUE THREAD

**Issue by jpm38** [bluebanquise/bluebanquise#958]
We need to use the DNS client role to configure the resolv.conf file with a DNS server no belonging to the networks defined in inventory.
We use the kubernetes coreDNS server belonging to another subnet (kube cluster IPs).

## Feature

The solution is to add a new "dns_client_server" optional  list variable.
When this variable is defined, the "nameserver" is configured with the content of this variable.

## Additional data

[If relevant, include a screenshot, links, etc.]

**Comment by oxedions** [comment]
Dear @jpm38 

Ok this makes sens :blush: 

I will do that asap !
