### ISSUE TITLE
[FEATURE REQUEST] Update default resolv.conf search

### ISSUE THREAD

**Issue by vedmonds** [bluebanquise/bluebanquise#962]
Recommending the initial variable used in the template be the role variable `dns_client_domain_name` then fallback to `bb_domain_name`.  

## Context

Given that `bb_domain_name` is likely to always be defined since it is used in a variety of other role contexts, which makes it more difficult to override it the variable precedence. 

In our case we want the `search` line to be a different value from `bb_domain_name` for this particular role only.  But because of how the template logic is written we are extremely limited in where we can override `bb_domain_name` without having ripple effects to other roles. (i.e. can't use host_vars, group_vars, inventory, includes)

## Feature

https://github.com/bluebanquise/bluebanquise/blob/master/collections/infrastructure/roles/dns_client/templates/resolv.conf.j2#L21

Flip the initial variable to be the role prefixed variable, then fallback to external variable:
`search {{ dns_client_domain_name | default(bb_domain_name) }}`

**Comment by oxedions** [comment]
Dear @vedmonds 

Thank you for this request.
You are right, and in fact, bb_ variables should always be precedenced by roles variables. This is a bug, I don't understand why I wrote the opposite in the code.
I will investigate all roles and fix this as soon as possible. :blush:

**Comment by oxedions** [comment]
Please check #963  :blush:
