### ISSUE TITLE
[FEATURE REQUEST] Cloud-init support for diskful & diskless

### ISSUE THREAD

**Issue by strus38** [bluebanquise/bluebanquise#964]
[Provide here general introduction to the feature request, and why it is relevant to this repository]

## Context

Cluster admin often need to execute pre-boot (at whatever stage between hw boot and ssh being available) scripts.
While i is do-able to setup in BB this mechanism via a service 'run-once' method, it would be nice to also be able to do it using clud-init method (https://cloudinit.readthedocs.io/en/latest/).

## Feature

1. Add a menu in disklessset to point to a cloud-init script.
2. Describe how to add a cloud-init file into a diskful image.

## Additional data

[If relevant, include a screenshot, links, etc.]

**Comment by oxedions** [comment]
Role has been created :blush:
