### ISSUE TITLE
[BUG] error while installing dhcp_server - starting dhcpd service before network interface got an ipv4 address

### ISSUE THREAD

**Issue by debbabi** [bluebanquise/bluebanquise#971]
## Context

In some cases, while installing the dhcp server, the service failed to start. 

```
TASK [bluebanquise.infrastructure.dhcp_server : service <|> Manage dhcpd state] ***
Tuesday 24 September 2024  17:03:45 +0200 (0:00:00.031)       0:00:16.607 ***** 
failed: [node1] (item=dhcpd) => {"ansible_loop_var": "item", "changed": false, "item": "dhcpd", "msg": "Unable to start service dhcpd: Job for dhcpd.service failed because the control process exited with error code.\nSee \"systemctl status dhcpd.service\" and \"journalctl -xeu dhcpd.service\" for details.\n"}
``` 

## Process

After investigating the issue, we found that while the dhcpd service was starting, the ipv4 address was not yet mounted to the network interface of the generated subnet configuration.

```
Sep 24 17:03:46 node1.cluster.local dhcpd[34618]: No subnet declaration for eno2 (no IPv4 addresses).
```

## Expected result

This is intermittent, we got the error multiple times when the dhcpd service startup was triggered before mounting the interwork interface to the subnet and gets an ipv4 address.

## Possible Fix

Add a waiting task to ensure that the ipv4 is set on the desired network interface before starting the service.

**Comment by oxedions** [comment]
Dear @debbabi 

Thank you for rising this issue. Since you closed the issue, does it means you solved it ?

**Comment by debbabi** [comment]
Hello @oxedions 
In our playbook, we have a call to bluebanquise.infrastructure.nic role before "bluebanquise.infrastructure.dhcp_server", which seems to not associate immediately an IP address to the network interface the time the dhcp_server role is called.  
For now, we think it should be not a problem of "bluebanquise.infrastructure.dhcp_server" as we should ensure that the network interface has an ipv4 before calling it.

**Comment by oxedions** [comment]
Dear @debbabi 

Thank you very much for this feedback !
Ok got it. Indeed, nmcli sometime takes time to up the network interfaces.

Happy to know your problem is solved by workaround :blush:
