### ISSUE TITLE
[BUG] UMASK on secured OS - "0027" instead of "0022"

### ISSUE THREAD

**Issue by strus38** [bluebanquise/bluebanquise#975]
[Provide general introduction to the issue logging and why it is relevant to this repository.]

## Context

Après avoir appliqué des règles de durcissement, le umask par défaut de l'OS est passé à "0027" au lieu de "0022".
Ainsi la commande `disklessset` génère ses fichiers avec ce mask ce qui empêche `httpd` d'accéder à ces fichiers; Par exemple:

```
####
$ ls -lha /var/www/html/preboot_execution_environment/diskless/images/compute6G-v1/squashfs.img
-rw-r-----. 1 root root 1.7G Oct  4 09:36 /var/www/html/preboot_execution_environment/diskless/images/compute6G-v1/squashfs.img
####
```

[Provide more detailed introduction to the issue context.]

Après avoir appliqué des règles de durcissement, le umask par défaut de l'OS est passé à "0027" au lieu de "0022".
Ainsi la commande `disklessset` génère ses fichiers avec ce mask ce qui empêche `httpd` d'accéder à ces fichiers; Par exemple:

```
####
$ ls -lha /var/www/html/preboot_execution_environment/diskless/images/compute6G-v1/squashfs.img
-rw-r-----. 1 root root 1.7G Oct  4 09:36 /var/www/html/preboot_execution_environment/diskless/images/compute6G-v1/squashfs.img
####
```

Here is a script to patch this behavior
```
####
$ diff -u  /tmp/disklessset /usr/bin/disklessset
--- /tmp/disklessset    2024-10-04 12:20:16.422494920 +0000
+++ /usr/bin/disklessset        2024-10-04 09:47:59.253494920 +0000
@@ -27,6 +27,7 @@

 # Import basic modules
 import sys
+import os
 import logging
 from termios import tcflush, TCIFLUSH

@@ -38,6 +39,7 @@

 # Main program
 if __name__ == "__main__":
+    os.umask(0o022)
     # Set logging logs level, this level can be configured in order to have more or less logging informations.
     # There are four levels (sorted by logs number): (lot of logs) DEBUG (default) > INFO > WARNING > ERROR (few logs)
     # Set logging level from the first argument
####
```

[Ordered list the process to finding and recreating the issue.]

## Expected result
The umask should not be changed, 

[Describe what you would expect to have resulted from this process.]

## Current result

[Describe what you you currently experience from this process, and thereby explain the bug.]

## Possible Fix

[Not mandatory, but suggest fixes or reasons for the bug.]

## Additional data

[If relevant, include a screenshot, links, etc.]

**Comment by oxedions** [comment]
Dear @strus38 

Thank you for raising this issue. This seems to be related to the old version of diskless, shipped with BB 1.X.
I do not support this version anymore. Could you test with a newer version and confirm the issue is still there ?
