### ISSUE TITLE
[BUG] Unnecessary leading comma in Clustershell Jinja2 template

### ISSUE THREAD

**Issue by lmagdanello** [bluebanquise/bluebanquise#983]
In the current Jinja2 template, when rendering group nodes, a leading comma is being added at the beginning of the list of nodes. This happens because the logic handling comma placement is manually checking whether the current iteration is the first.

When nodes are filtered, the condition `loop.first` still evaluates as True for subsequent elements after filtering, which results in an extra comma being placed at the beginning of the output. Example:

```bash
all: ,pm1-emc0,pm1-emc1,...
```

**Comment by oxedions** [comment]
Dear @lmagdanello 

Thank you very much for this issue :blush: 
I added a small request on the PR.
