### ISSUE TITLE
[BUG] PXE Boot Fails with 'TFTP Open Timeout' Using fbtftp_server on Rocky Linux 9

### ISSUE THREAD

**Issue by allancarlosvr** [bluebanquise/bluebanquise#991]
[Provide general introduction to the issue logging and why it is relevant to this repository.]

## Context

I am setting up a PXE boot environment using fbtftp_server on a Rocky Linux 9 server. The PXE boot setup is designed to serve bootloaders (undionly.kpxe for BIOS and ipxe.efi for UEFI) to client nodes via TFTP. The fbtftp_server is running as a systemd service, and the DHCP server is configured to provide the necessary PXE options.

The issue arises when PXE clients fail with a TFTP open timeout error, even though the TFTP server appears to be running correctly.

## Process

1. Installed fbtftp_server and configured it to serve files from /var/lib/tftpboot/.
2. Added the necessary bootloader files (undionly.kpxe and ipxe.efi) to /var/lib/tftpboot/.
3. Configured DHCP with the following PXE options:
`next-server 10.77.0.1;
if exists user-class and option user-class = "iPXE" {
    filename "boot.ipxe";
} else {
    if option client-arch = 00:00 {
        filename "undionly.kpxe";
    } elsif option client-arch = 00:07 {
        filename "ipxe.efi";
    }
}
`

4 - Started the fbtftp_server service:
`systemctl start fbtftp_server`

5. Booted a PXE client (VirtualBox VM) and observed the error PXE-E32: TFTP open timeout, but received a valid IP from DHCP

## Expected result

The PXE client should successfully retrieve the bootloader file (undionly.kpxe or ipxe.efi) from the TFTP server and proceed with the boot process

## Current result

The PXE client receives a DHCP lease and obtains the TFTP server IP address but fails with a TFTP open timeout error. Logs confirm that the fbtftp_server service is running, but the client cannot connect to it.

Relevant logs:

- dhcp
`DHCPDISCOVER from 08:00:27:fc:e7:43 via eth2
DHCPOFFER on 10.77.0.2 to 08:00:27:fc:e7:43 via eth2
DHCPREQUEST for 10.77.0.2 (10.77.0.1) from 08:00:27:fc:e7:43 via eth2
DHCPACK on 10.77.0.2 to 08:00:27:fc:e7:43 via eth2
`
- tftp
`PXE-E32: TFTP open timeout`

## Additional data
	
I was followed this tutorial 

https://bluebanquise.com/tutorials/sysadmin_servers_farm_deployment/

But, in my test I configured a master node (management), and I want to deploy 2 compute nodes (VM's in Virtualbox provided with Vagrant)

**Comment by oxedions** [comment]
Dear @allancarlosvr 

Thank you for rising this issue ! :blush: 

Ok, lets try all in the debug way.

1. Can you check no the fbtftp logs that you got "something" ? A connection log.
2. Can you check your firewall ? By default, firewalld on RHEL 9 does not let TFTP request come in. If environment is safe, try to disable it during the test and check if it works.
3. Try to comment in the dhcp server all conditionals:
```
next-server 10.77.0.1;
filename "ipxe.efi";
```
4. Try to query the tftp manually, to ensure it at least respond. To do so, install the RHEL tftp client, and connect to your server:
`tftp 10.77.0.1`

Then request a file and check it works:
`get ipxe.efi`

Now on the client server side:
Go into the BIOS, and check the boot method. Try to not use DUAL mode some vendors are making default. In DUAL, you cannot predict if the node will boot in EFI or Legacy. If the server is >= SandyBridge/IvyBridge generation, use EFI boot. If before (mostly <= Nehalem/Westmer), I would prefer legacy as EFI was not properly supported as I could see.

Other things to check is:
* Do you have some VLANs setup on your network ?

Let me know !

**Comment by allancarlosvr** [comment]
I tried to configure a new lab, following and replicate the tutorial:

https://bluebanquise.com/tutorials/sysadmin_servers_farm_deployment/

I passed for the next phase, but still showing error in PXE Boot process, but refer **autoexec.ipxe Not found** 

Mode details in the image attached

<img width="401" alt="image" src="https://github.com/user-attachments/assets/f20f42d0-5515-4abd-9926-597b2997b3a9">

**Comment by oxedions** [comment]
Dear @allancarlosvr 

The autoexec.ipxe should be optional. Its an ipxe feature that was added few years ago. You can try to use it if you want, it could replace the concept of the embed script I propose in the tutorial.

Are you able to see the autoexec.ipxe get inside the logs of your tftp server ?

**Comment by allancarlosvr** [comment]
Dear @oxedions I solved my issue following this documentation
https://bluebanquise.com/documentation/deploy_cluster.html

**Comment by oxedions** [comment]
Dear @allancarlosvr 
Another user also faced the same PXE issue with the tutorial. I made a proposal solution there: https://github.com/bluebanquise/bluebanquise/discussions/995

I hope it will help.
